package io.quarkus.qusaq.deployment;

import io.quarkus.qusaq.deployment.analysis.CallSiteProcessor;
import io.quarkus.qusaq.deployment.analysis.LambdaBytecodeAnalyzer;
import io.quarkus.qusaq.deployment.analysis.LambdaDeduplicator;
import io.quarkus.qusaq.deployment.generation.QueryExecutorClassGenerator;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests to verify missing coverage for Cast, InstanceOf, and Conditional expression types.
 *
 * <p>These tests document and verify that {@code collectCapturedVariableIndices()} does NOT
 * handle the following expression types:
 * <ul>
 *   <li>{@link LambdaExpression.Cast}</li>
 *   <li>{@link LambdaExpression.InstanceOf}</li>
 *   <li>{@link LambdaExpression.Conditional}</li>
 * </ul>
 *
 * <p>This is intentional because these expression types are:
 * <ol>
 *   <li>Never generated by the bytecode analyzer in production code</li>
 *   <li>Only exist in unit tests for the LambdaExpression data structures</li>
 *   <li>Not part of the supported query lambda syntax</li>
 * </ol>
 *
 * <p>These tests verify that IF these types were ever used in production (which they aren't),
 * any captured variables within them would be silently ignored, resulting in incorrect
 * captured variable counts.
 *
 * <p><strong>Context:</strong> The {@code containsCapturedVariables()} method was removed
 * because it was redundant (just checking {@code countCapturedVariables() > 0} provides the
 * same information). During removal, we identified that both methods had the same gap in
 * coverage for these three expression types. These tests document this gap and verify that
 * it exists as expected.
 */
class CapturedVariableCoverageTest {

    /**
     * Helper method to invoke the private collectCapturedVariableIndices method via reflection.
     */
    private Set<Integer> collectCapturedVariables(LambdaExpression expression) throws Exception {
        CallSiteProcessor processor = new CallSiteProcessor(
                new LambdaBytecodeAnalyzer(),
                new LambdaDeduplicator(),
                new QueryExecutorClassGenerator(),
                new AtomicInteger(0));
        Set<Integer> capturedIndices = new HashSet<>();

        Method method = CallSiteProcessor.class.getDeclaredMethod(
                "collectCapturedVariableIndices",
                LambdaExpression.class,
                Set.class);
        method.setAccessible(true);
        method.invoke(processor, expression, capturedIndices);

        return capturedIndices;
    }

    /**
     * Helper method to invoke the private countCapturedVariables method via reflection.
     */
    private int countCapturedVariables(LambdaExpression expression) throws Exception {
        CallSiteProcessor processor = new CallSiteProcessor(
                new LambdaBytecodeAnalyzer(),
                new LambdaDeduplicator(),
                new QueryExecutorClassGenerator(),
                new AtomicInteger(0));

        Method method = CallSiteProcessor.class.getDeclaredMethod(
                "countCapturedVariables",
                LambdaExpression.class);
        method.setAccessible(true);

        return (int) method.invoke(processor, expression);
    }

    // ========================================================================
    // Tests for Cast Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testCastExpression_withCapturedVariable_missesVariable() throws Exception {
        // Create a Cast expression containing a captured variable
        // Pattern: (String) capturedVar
        var capturedVar = new LambdaExpression.CapturedVariable(0, Object.class);
        var cast = new LambdaExpression.Cast(capturedVar, String.class);

        // Verify that the captured variable is MISSED (not detected)
        Set<Integer> capturedIndices = collectCapturedVariables(cast);

        assertThat(capturedIndices)
                .as("Cast expression should NOT detect captured variables in its child expression")
                .isEmpty();
    }

    @Test
    void testCastExpression_withNestedCapturedVariable_missesVariable() throws Exception {
        // Create a more complex Cast expression with nested captured variable
        // Pattern: (Integer) (capturedVar + 5)
        var capturedVar = new LambdaExpression.CapturedVariable(1, Integer.class);
        var constant = new LambdaExpression.Constant(5, Integer.class);
        var addition = new LambdaExpression.BinaryOp(
                capturedVar,
                LambdaExpression.BinaryOp.Operator.ADD,
                constant);
        var cast = new LambdaExpression.Cast(addition, Integer.class);

        // The BinaryOp would normally traverse its children, but since it's wrapped in Cast,
        // the Cast is the entry point and it doesn't traverse its child
        Set<Integer> capturedIndices = collectCapturedVariables(cast);

        assertThat(capturedIndices)
                .as("Cast expression should NOT detect captured variables even when nested in supported types")
                .isEmpty();
    }

    @Test
    void testCastExpression_countCapturedVariables_returnsZero() throws Exception {
        // Verify that countCapturedVariables also misses variables in Cast expressions
        var capturedVar = new LambdaExpression.CapturedVariable(0, Object.class);
        var cast = new LambdaExpression.Cast(capturedVar, String.class);

        int count = countCapturedVariables(cast);

        assertThat(count)
                .as("countCapturedVariables should return 0 for Cast expressions")
                .isZero();
    }

    // ========================================================================
    // Tests for InstanceOf Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testInstanceOfExpression_withCapturedVariable_missesVariable() throws Exception {
        // Create an InstanceOf expression containing a captured variable
        // Pattern: capturedVar instanceof String
        var capturedVar = new LambdaExpression.CapturedVariable(0, Object.class);
        var instanceOf = new LambdaExpression.InstanceOf(capturedVar, String.class);

        // Verify that the captured variable is MISSED (not detected)
        Set<Integer> capturedIndices = collectCapturedVariables(instanceOf);

        assertThat(capturedIndices)
                .as("InstanceOf expression should NOT detect captured variables in its child expression")
                .isEmpty();
    }

    @Test
    void testInstanceOfExpression_withComplexChild_missesVariable() throws Exception {
        // Create an InstanceOf expression with a method call containing captured variable
        // Pattern: capturedVar.getValue() instanceof String
        var capturedVar = new LambdaExpression.CapturedVariable(2, Object.class);
        var methodCall = new LambdaExpression.MethodCall(
                capturedVar,
                "getValue",
                List.of(),
                Object.class);
        var instanceOf = new LambdaExpression.InstanceOf(methodCall, String.class);

        // The MethodCall would normally traverse its target, but since it's wrapped in InstanceOf,
        // the InstanceOf is the entry point and it doesn't traverse its child
        Set<Integer> capturedIndices = collectCapturedVariables(instanceOf);

        assertThat(capturedIndices)
                .as("InstanceOf expression should NOT detect captured variables even in complex child expressions")
                .isEmpty();
    }

    @Test
    void testInstanceOfExpression_countCapturedVariables_returnsZero() throws Exception {
        // Verify that countCapturedVariables also misses variables in InstanceOf expressions
        var capturedVar = new LambdaExpression.CapturedVariable(0, Object.class);
        var instanceOf = new LambdaExpression.InstanceOf(capturedVar, String.class);

        int count = countCapturedVariables(instanceOf);

        assertThat(count)
                .as("countCapturedVariables should return 0 for InstanceOf expressions")
                .isZero();
    }

    // ========================================================================
    // Tests for Conditional Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testConditionalExpression_withCapturedVariableInCondition_missesVariable() throws Exception {
        // Create a Conditional expression with captured variable in condition
        // Pattern: capturedFlag ? "yes" : "no"
        var capturedVar = new LambdaExpression.CapturedVariable(0, Boolean.class);
        var trueValue = new LambdaExpression.Constant("yes", String.class);
        var falseValue = new LambdaExpression.Constant("no", String.class);
        var conditional = new LambdaExpression.Conditional(capturedVar, trueValue, falseValue);

        // Verify that the captured variable in condition is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditional);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in condition")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withCapturedVariableInTrueValue_missesVariable() throws Exception {
        // Create a Conditional expression with captured variable in true value
        // Pattern: active ? capturedName : "Unknown"
        var condition = new LambdaExpression.FieldAccess("active", Boolean.class);
        var capturedVar = new LambdaExpression.CapturedVariable(1, String.class);
        var falseValue = new LambdaExpression.Constant("Unknown", String.class);
        var conditional = new LambdaExpression.Conditional(condition, capturedVar, falseValue);

        // Verify that the captured variable in true value is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditional);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in true value")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withCapturedVariableInFalseValue_missesVariable() throws Exception {
        // Create a Conditional expression with captured variable in false value
        // Pattern: active ? "Active" : capturedStatus
        var condition = new LambdaExpression.FieldAccess("active", Boolean.class);
        var trueValue = new LambdaExpression.Constant("Active", String.class);
        var capturedVar = new LambdaExpression.CapturedVariable(2, String.class);
        var conditional = new LambdaExpression.Conditional(condition, trueValue, capturedVar);

        // Verify that the captured variable in false value is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditional);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in false value")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withMultipleCapturedVariables_missesAll() throws Exception {
        // Create a Conditional expression with captured variables in all three positions
        // Pattern: capturedFlag ? capturedName : capturedDefault
        var capturedCondition = new LambdaExpression.CapturedVariable(0, Boolean.class);
        var capturedTrue = new LambdaExpression.CapturedVariable(1, String.class);
        var capturedFalse = new LambdaExpression.CapturedVariable(2, String.class);
        var conditional = new LambdaExpression.Conditional(
                capturedCondition,
                capturedTrue,
                capturedFalse);

        // Verify that ALL three captured variables are MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditional);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in any position")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_countCapturedVariables_returnsZero() throws Exception {
        // Verify that countCapturedVariables also misses variables in Conditional expressions
        var capturedVar = new LambdaExpression.CapturedVariable(0, Boolean.class);
        var trueValue = new LambdaExpression.Constant("yes", String.class);
        var falseValue = new LambdaExpression.Constant("no", String.class);
        var conditional = new LambdaExpression.Conditional(capturedVar, trueValue, falseValue);

        int count = countCapturedVariables(conditional);

        assertThat(count)
                .as("countCapturedVariables should return 0 for Conditional expressions")
                .isZero();
    }

    // ========================================================================
    // Baseline Tests (Verify that supported types DO detect variables)
    // ========================================================================

    @Test
    void testSupportedTypes_detectCapturedVariables() throws Exception {
        // Verify that the supported expression types DO correctly detect captured variables
        // This serves as a baseline to confirm the test methodology is correct

        // Test BinaryOp (supported)
        var capturedVar1 = new LambdaExpression.CapturedVariable(0, Integer.class);
        var constant = new LambdaExpression.Constant(5, Integer.class);
        var binaryOp = new LambdaExpression.BinaryOp(
                capturedVar1,
                LambdaExpression.BinaryOp.Operator.GT,
                constant);

        assertThat(collectCapturedVariables(binaryOp))
                .as("BinaryOp should correctly detect captured variables")
                .containsExactly(0);

        // Test UnaryOp (supported)
        var capturedVar2 = new LambdaExpression.CapturedVariable(1, Boolean.class);
        var unaryOp = new LambdaExpression.UnaryOp(
                LambdaExpression.UnaryOp.Operator.NOT,
                capturedVar2);

        assertThat(collectCapturedVariables(unaryOp))
                .as("UnaryOp should correctly detect captured variables")
                .containsExactly(1);

        // Test MethodCall (supported)
        var capturedVar3 = new LambdaExpression.CapturedVariable(2, String.class);
        var methodCall = new LambdaExpression.MethodCall(
                capturedVar3,
                "toLowerCase",
                List.of(),
                String.class);

        assertThat(collectCapturedVariables(methodCall))
                .as("MethodCall should correctly detect captured variables in target")
                .containsExactly(2);
    }

    @Test
    void testDirectCapturedVariable_isDetected() throws Exception {
        // Verify that a direct CapturedVariable is always detected
        var capturedVar = new LambdaExpression.CapturedVariable(5, String.class);

        assertThat(collectCapturedVariables(capturedVar))
                .as("Direct CapturedVariable should be detected")
                .containsExactly(5);

        assertThat(countCapturedVariables(capturedVar))
                .as("countCapturedVariables should return 1 for direct CapturedVariable")
                .isEqualTo(1);
    }
}
