package io.quarkiverse.qubit.deployment.generation;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import io.quarkiverse.qubit.SortDirection;
import io.quarkiverse.qubit.deployment.analysis.LambdaAnalysisResult.SortExpression;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression.BinaryOp;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression.CapturedVariable;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression.Constant;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression.FieldAccess;
import io.quarkiverse.qubit.runtime.internal.QueryExecutor;

/**
 * End-to-end tests for {@link QueryExecutorClassGenerator}.
 *
 * <p>
 * Generates bytecode via Gizmo2, loads it with a custom classloader,
 * instantiates the generated {@link QueryExecutor}, and executes it
 * against an in-memory H2 database with Hibernate ORM.
 *
 * <p>
 * Test data:
 *
 * <pre>
 * | name    | age | department  | salary   | active |
 * |---------|-----|-------------|----------|--------|
 * | Alice   |  30 | Engineering | 85000.0  | true   |
 * | Bob     |  25 | Marketing   | 65000.0  | true   |
 * | Charlie |  45 | Engineering | 95000.0  | false  |
 * | Diana   |  35 | Marketing   | 75000.0  | true   |
 * </pre>
 */
@DisplayName("QueryExecutorClassGenerator")
class QueryExecutorClassGeneratorTest {

    private static EntityManagerFactory emf;
    private static QueryExecutorClassGenerator generator;
    private EntityManager em;

    @BeforeAll
    static void setupJpa() {
        Configuration config = new Configuration();
        config.setProperty("hibernate.connection.driver_class", "org.h2.Driver");
        config.setProperty("hibernate.connection.url", "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1");
        config.setProperty("hibernate.connection.username", "sa");
        config.setProperty("hibernate.connection.password", "");
        config.setProperty("hibernate.hbm2ddl.auto", "create-drop");
        config.setProperty("hibernate.show_sql", "false");
        config.addAnnotatedClass(TestPerson.class);

        // SessionFactory extends EntityManagerFactory in Hibernate
        emf = config.buildSessionFactory();

        // Clear the static bytecode cache to avoid cross-test interference
        QueryExecutorClassGenerator.clearCache();
        generator = new QueryExecutorClassGenerator();

        // Insert test data
        EntityManager setupEm = emf.createEntityManager();
        setupEm.getTransaction().begin();
        setupEm.persist(new TestPerson("Alice", 30, "Engineering", 85000.0, true));
        setupEm.persist(new TestPerson("Bob", 25, "Marketing", 65000.0, true));
        setupEm.persist(new TestPerson("Charlie", 45, "Engineering", 95000.0, false));
        setupEm.persist(new TestPerson("Diana", 35, "Marketing", 75000.0, true));
        setupEm.getTransaction().commit();
        setupEm.close();
    }

    @BeforeEach
    void setupEntityManager() {
        em = emf.createEntityManager();
    }

    @AfterEach
    void closeEntityManager() {
        if (em != null && em.isOpen()) {
            em.close();
        }
    }

    @AfterAll
    static void tearDown() {
        if (emf != null) {
            emf.close();
        }
    }

    // --- Test entity ---

    @Entity
    @Table(name = "test_person")
    static class TestPerson {
        @Id
        @GeneratedValue
        public Long id;
        public String name;
        public int age;
        public String department;
        public double salary;
        public boolean active;

        public TestPerson() {
        }

        public TestPerson(String name, int age, String department, double salary, boolean active) {
            this.name = name;
            this.age = age;
            this.department = department;
            this.salary = salary;
            this.active = active;
        }
    }

    // --- Helper method ---

    /**
     * Loads the generated bytecode with a custom classloader, instantiates
     * the {@link QueryExecutor}, and executes it against the test EntityManager.
     */
    @SuppressWarnings("unchecked")
    private <T> T executeGeneratedQuery(byte[] bytecode, String className, Object[] capturedValues,
            Integer offset, Integer limit, Boolean distinct) throws Exception {

        ClassLoader cl = new ClassLoader(getClass().getClassLoader()) {
            @Override
            protected Class<?> findClass(String name) throws ClassNotFoundException {
                if (name.equals(className)) {
                    return defineClass(name, bytecode, 0, bytecode.length);
                }
                throw new ClassNotFoundException(name);
            }
        };

        Class<?> executorClass = cl.loadClass(className);
        QueryExecutor<T> executor = (QueryExecutor<T>) executorClass.getDeclaredConstructor().newInstance();
        return executor.execute(em, TestPerson.class,
                capturedValues != null ? capturedValues : new Object[0],
                offset, limit, distinct);
    }

    // --- Test cases ---

    @Test
    @DisplayName("1. Simple WHERE predicate: age > 30")
    void simpleWherePredicate() throws Exception {
        // WHERE age > 30
        LambdaExpression predicate = BinaryOp.gt(
                new FieldAccess("age", int.class),
                new Constant(30, int.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec1", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec1", null, null, null, null);
        assertThat(results).hasSize(2); // Charlie(45), Diana(35)
    }

    @Test
    @DisplayName("2. SELECT field projection: name")
    void selectFieldProjection() throws Exception {
        // SELECT name (all rows)
        LambdaExpression projection = new FieldAccess("name", String.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, projection, List.of(), null, null,
                "io.test.Exec2", false, false);

        List<String> results = executeGeneratedQuery(bytecode, "io.test.Exec2", null, null, null, null);
        assertThat(results).hasSize(4)
                .containsExactlyInAnyOrder("Alice", "Bob", "Charlie", "Diana");
    }

    @Test
    @DisplayName("3. Combined WHERE + SELECT: active=true, select name")
    void combinedWhereSelect() throws Exception {
        // WHERE active = true, SELECT name
        LambdaExpression predicate = new FieldAccess("active", boolean.class);
        LambdaExpression projection = new FieldAccess("name", String.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, projection, List.of(), null, null,
                "io.test.Exec3", false, false);

        List<String> results = executeGeneratedQuery(bytecode, "io.test.Exec3", null, null, null, null);
        assertThat(results).hasSize(3)
                .containsExactlyInAnyOrder("Alice", "Bob", "Diana");
    }

    @Test
    @DisplayName("4. Sort-only query: ORDER BY age ASC")
    void sortOnlyQuery() throws Exception {
        // ORDER BY age ASC
        List<SortExpression> sorts = List.of(
                new SortExpression(new FieldAccess("age", int.class), SortDirection.ASCENDING));

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, sorts, null, null,
                "io.test.Exec4", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec4", null, null, null, null);
        assertThat(results).hasSize(4);
        // First result should be youngest (Bob=25)
        assertThat(((TestPerson) results.get(0)).age).isEqualTo(25);
        // Last result should be oldest (Charlie=45)
        assertThat(((TestPerson) results.get(3)).age).isEqualTo(45);
    }

    @Test
    @DisplayName("5. Count query: COUNT WHERE active=true")
    void countQuery() throws Exception {
        // COUNT WHERE active = true
        LambdaExpression predicate = new FieldAccess("active", boolean.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec5", true, false);

        Long count = executeGeneratedQuery(bytecode, "io.test.Exec5", null, null, null, null);
        assertThat(count).isEqualTo(3L);
    }

    @Test
    @DisplayName("6. Pagination: ORDER BY name ASC, skip 1, limit 2")
    void paginationQuery() throws Exception {
        // All rows, ORDER BY name ASC, skip 1, limit 2
        List<SortExpression> sorts = List.of(
                new SortExpression(new FieldAccess("name", String.class), SortDirection.ASCENDING));

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, sorts, null, null,
                "io.test.Exec6", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec6", null, 1, 2, null);
        assertThat(results).hasSize(2);
        // Sorted by name: Alice, Bob, Charlie, Diana -> skip Alice -> Bob, Charlie
        assertThat(((TestPerson) results.get(0)).name).isEqualTo("Bob");
        assertThat(((TestPerson) results.get(1)).name).isEqualTo("Charlie");
    }

    @Test
    @DisplayName("7. Distinct query: SELECT DISTINCT department")
    void distinctQuery() throws Exception {
        // SELECT DISTINCT department
        LambdaExpression projection = new FieldAccess("department", String.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, projection, List.of(), null, null,
                "io.test.Exec7", false, false);

        List<String> results = executeGeneratedQuery(bytecode, "io.test.Exec7", null, null, null, true);
        assertThat(results).hasSize(2)
                .containsExactlyInAnyOrder("Engineering", "Marketing");
    }

    @Test
    @DisplayName("8. Captured variables in predicate: age > capturedValues[0]")
    void capturedVariablesInPredicate() throws Exception {
        // WHERE age > capturedValues[0] (where capturedValues[0] = 30)
        LambdaExpression predicate = BinaryOp.gt(
                new FieldAccess("age", int.class),
                new CapturedVariable(0, int.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec8", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec8",
                new Object[] { 30 }, null, null, null);
        assertThat(results).hasSize(2); // Charlie(45), Diana(35)
    }

    @Test
    @DisplayName("9. MIN aggregation: MIN(age)")
    void minAggregation() throws Exception {
        // MIN(age)
        LambdaExpression aggField = new FieldAccess("age", int.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, List.of(), aggField, "MIN",
                "io.test.Exec9", false, true);

        Object result = executeGeneratedQuery(bytecode, "io.test.Exec9", null, null, null, null);
        assertThat(result).isEqualTo(25); // Bob is youngest
    }

    @Test
    @DisplayName("10. MAX aggregation: MAX(salary)")
    void maxAggregation() throws Exception {
        // MAX(salary)
        LambdaExpression aggField = new FieldAccess("salary", double.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, List.of(), aggField, "MAX",
                "io.test.Exec10", false, true);

        Object result = executeGeneratedQuery(bytecode, "io.test.Exec10", null, null, null, null);
        assertThat(result).isEqualTo(95000.0);
    }

    @Test
    @DisplayName("11. AVG aggregation: AVG(salary)")
    void avgAggregation() throws Exception {
        // AVG(salary)
        LambdaExpression aggField = new FieldAccess("salary", double.class);

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, List.of(), aggField, "AVG",
                "io.test.Exec11", false, true);

        Object result = executeGeneratedQuery(bytecode, "io.test.Exec11", null, null, null, null);
        assertThat((Double) result).isCloseTo(80000.0, within(0.01));
    }

    @Test
    @DisplayName("12. WHERE with AND: age > 25 AND active = true")
    void whereWithAndPredicate() throws Exception {
        // WHERE age > 25 AND active = true
        LambdaExpression predicate = BinaryOp.and(
                BinaryOp.gt(
                        new FieldAccess("age", int.class),
                        new Constant(25, int.class)),
                new FieldAccess("active", boolean.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec12", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec12", null, null, null, null);
        // age>25 AND active: Alice(30,true), Diana(35,true) -- not Bob(25) and not Charlie(false)
        assertThat(results).hasSize(2);
    }

    @Test
    @DisplayName("13. Sort descending: ORDER BY salary DESC")
    void sortDescendingQuery() throws Exception {
        // ORDER BY salary DESC
        List<SortExpression> sorts = List.of(
                new SortExpression(new FieldAccess("salary", double.class), SortDirection.DESCENDING));

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, sorts, null, null,
                "io.test.Exec13", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec13", null, null, null, null);
        assertThat(results).hasSize(4);
        // Highest salary first: Charlie(95000)
        assertThat(((TestPerson) results.get(0)).salary).isEqualTo(95000.0);
        // Lowest salary last: Bob(65000)
        assertThat(((TestPerson) results.get(3)).salary).isEqualTo(65000.0);
    }

    @Test
    @DisplayName("14. WHERE with string equality: department == 'Engineering'")
    void whereStringEquality() throws Exception {
        // WHERE department == "Engineering"
        LambdaExpression predicate = BinaryOp.eq(
                new FieldAccess("department", String.class),
                new Constant("Engineering", String.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec14", false, false);

        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec14", null, null, null, null);
        assertThat(results).hasSize(2); // Alice, Charlie
    }

    @Test
    @DisplayName("15. Count all rows (no WHERE)")
    void countAllQuery() throws Exception {
        // COUNT all (no predicate)
        byte[] bytecode = generator.generateQueryExecutorClass(
                null, null, List.of(), null, null,
                "io.test.Exec15", true, false);

        Long count = executeGeneratedQuery(bytecode, "io.test.Exec15", null, null, null, null);
        assertThat(count).isEqualTo(4L);
    }

    @Test
    @DisplayName("16a. Captured variables in both predicate and projection (Bug B - index collision)")
    void capturedVariablesInPredicateAndProjection() throws Exception {
        // Verifies the generator handles distinct captured variable indices across
        // predicate and projection. The ASTs here use PRE-RENUMBERED indices
        // (predicate=0, projection=1) as SimpleQueryHandler would produce after
        // calling CapturedVariableHelper.renumberCapturedVariables().
        // The renumbering pipeline itself is tested via integration tests.
        LambdaExpression predicate = BinaryOp.gt(
                new FieldAccess("age", int.class),
                new CapturedVariable(0, int.class));

        LambdaExpression projection = BinaryOp.add(
                new FieldAccess("salary", double.class),
                new CapturedVariable(1, double.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, projection, List.of(), null, null,
                "io.test.Exec16a", false, false);

        // capturedValues[0] = 30 (minAge), capturedValues[1] = 1000.0 (bonus)
        List<Double> results = executeGeneratedQuery(bytecode, "io.test.Exec16a",
                new Object[] { 30, 1000.0 }, null, null, null);
        // age > 30: Charlie(45, 95000), Diana(35, 75000) → salary + bonus
        assertThat(results).hasSize(2)
                .containsExactlyInAnyOrder(96000.0, 76000.0);
    }

    @Test
    @DisplayName("16b. Captured variable in projection only (Bug A - runtime extraction)")
    void capturedVariableInProjectionOnly() throws Exception {
        // No WHERE, SELECT salary + capturedValues[0] (bonus = 5000.0)
        LambdaExpression projection = BinaryOp.add(
                new FieldAccess("salary", double.class),
                new CapturedVariable(0, double.class));

        byte[] bytecode = generator.generateQueryExecutorClass(
                null, projection, List.of(), null, null,
                "io.test.Exec16b", false, false);

        List<Double> results = executeGeneratedQuery(bytecode, "io.test.Exec16b",
                new Object[] { 5000.0 }, null, null, null);
        // All 4 rows: salary + 5000
        assertThat(results).hasSize(4)
                .containsExactlyInAnyOrder(90000.0, 70000.0, 100000.0, 80000.0);
    }

    @Test
    @DisplayName("16. Multiple captured variables: age > cv[0] AND salary < cv[1]")
    void multipleCapturedVariables() throws Exception {
        // WHERE age > capturedValues[0] AND salary < capturedValues[1]
        LambdaExpression predicate = BinaryOp.and(
                BinaryOp.gt(
                        new FieldAccess("age", int.class),
                        new CapturedVariable(0, int.class)),
                BinaryOp.lt(
                        new FieldAccess("salary", double.class),
                        new CapturedVariable(1, double.class)));

        byte[] bytecode = generator.generateQueryExecutorClass(
                predicate, null, List.of(), null, null,
                "io.test.Exec16", false, false);

        // age > 30 AND salary < 80000.0 -> Diana(35, 75000.0)
        List<?> results = executeGeneratedQuery(bytecode, "io.test.Exec16",
                new Object[] { 30, 80000.0 }, null, null, null);
        assertThat(results).hasSize(1);
        assertThat(((TestPerson) results.get(0)).name).isEqualTo("Diana");
    }
}
