package io.quarkiverse.qubit.deployment.util;

import io.quarkus.gizmo.ClassOutput;

/** ClassOutput that captures generated bytecode into a byte array. */
public final class ByteArrayClassOutput implements ClassOutput {

    private byte[] data;

    public ByteArrayClassOutput() {
        // Default constructor - data is set via write()
    }

    @Override
    public void write(String name, byte[] data) {
        this.data = data;
    }

    /** Returns the captured bytecode data, or null if write() has not been called. */
    public byte[] getData() {
        return data;
    }
}
