package io.quarkiverse.qubit.deployment.util;

import io.quarkus.gizmo.ClassOutput;

/**
 * A simple {@link ClassOutput} implementation that captures generated bytecode
 * into a byte array for later use.
 *
 * <p>This class is used by query executor generators to capture the bytecode
 * of dynamically generated classes.
 *
 * @see io.quarkiverse.qubit.deployment.generation.QueryExecutorClassGenerator
 */
public final class ByteArrayClassOutput implements ClassOutput {

    private byte[] data;

    /**
     * Creates a new ByteArrayClassOutput with no data.
     */
    public ByteArrayClassOutput() {
        // Default constructor
    }

    @Override
    public void write(String name, byte[] data) {
        this.data = data;
    }

    /**
     * Returns the captured bytecode data.
     *
     * @return the bytecode data, or null if {@link #write} has not been called
     */
    public byte[] getData() {
        return data;
    }
}
