package io.quarkiverse.qubit.deployment.analysis;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link MethodScanState} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractMethodScanStateAssert<S extends AbstractMethodScanStateAssert<S, A>, A extends MethodScanState>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractMethodScanStateAssert}</code> to make assertions on actual MethodScanState.
     *
     * @param actual the MethodScanState we want to make assertions on.
     */
    protected AbstractMethodScanStateAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual MethodScanState has distinct.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState does not have distinct.
     */
    public S hasDistinct() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasDistinct()) {
            failWithMessage("\nExpecting that actual MethodScanState has distinct but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState does not have distinct.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState has distinct.
     */
    public S doesNotHaveDistinct() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasDistinct()) {
            failWithMessage("\nExpecting that actual MethodScanState does not have distinct but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState is group context.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState is not group context.
     */
    public S isGroupContext() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isGroupContext()) {
            failWithMessage("\nExpecting that actual MethodScanState is group context but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState is not group context.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState is group context.
     */
    public S isNotGroupContext() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isGroupContext()) {
            failWithMessage("\nExpecting that actual MethodScanState is not group context but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState is join context.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState is not join context.
     */
    public S isJoinContext() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isJoinContext()) {
            failWithMessage("\nExpecting that actual MethodScanState is join context but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState is not join context.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState is join context.
     */
    public S isNotJoinContext() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isJoinContext()) {
            failWithMessage("\nExpecting that actual MethodScanState is not join context but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState has lambdas.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState does not have lambdas.
     */
    public S hasLambdas() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasLambdas()) {
            failWithMessage("\nExpecting that actual MethodScanState has lambdas but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual MethodScanState does not have lambdas.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual MethodScanState has lambdas.
     */
    public S doesNotHaveLambdas() {
        // check that actual MethodScanState we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasLambdas()) {
            failWithMessage("\nExpecting that actual MethodScanState does not have lambdas but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

}
