package io.quarkiverse.qubit.deployment.analysis;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link QueryExecutionPlan} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractQueryExecutionPlanAssert<S extends AbstractQueryExecutionPlanAssert<S, A>, A extends QueryExecutionPlan>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractQueryExecutionPlanAssert}</code> to make assertions on actual QueryExecutionPlan.
     *
     * @param actual the QueryExecutionPlan we want to make assertions on.
     */
    protected AbstractQueryExecutionPlanAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual QueryExecutionPlan has distinct.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryExecutionPlan does not have distinct.
     */
    public S hasDistinct() {
        // check that actual QueryExecutionPlan we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasDistinct()) {
            failWithMessage("\nExpecting that actual QueryExecutionPlan has distinct but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryExecutionPlan does not have distinct.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryExecutionPlan has distinct.
     */
    public S doesNotHaveDistinct() {
        // check that actual QueryExecutionPlan we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasDistinct()) {
            failWithMessage("\nExpecting that actual QueryExecutionPlan does not have distinct but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

}
