package io.quarkiverse.qubit.deployment.analysis;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link AnalysisOutcome} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractAnalysisOutcomeAssert<S extends AbstractAnalysisOutcomeAssert<S, A>, A extends AnalysisOutcome>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractAnalysisOutcomeAssert}</code> to make assertions on actual AnalysisOutcome.
     *
     * @param actual the AnalysisOutcome we want to make assertions on.
     */
    protected AbstractAnalysisOutcomeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual AnalysisOutcome can continue.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisOutcome cannot continue.
     */
    public S canContinue() {
        // check that actual AnalysisOutcome we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.canContinue()) {
            failWithMessage("\nExpecting that actual AnalysisOutcome can continue but cannot.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisOutcome cannot continue.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisOutcome can continue.
     */
    public S cannotContinue() {
        // check that actual AnalysisOutcome we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.canContinue()) {
            failWithMessage("\nExpecting that actual AnalysisOutcome cannot continue but can.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisOutcome is success.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisOutcome is not success.
     */
    public S isSuccess() {
        // check that actual AnalysisOutcome we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isSuccess()) {
            failWithMessage("\nExpecting that actual AnalysisOutcome is success but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisOutcome is not success.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisOutcome is success.
     */
    public S isNotSuccess() {
        // check that actual AnalysisOutcome we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isSuccess()) {
            failWithMessage("\nExpecting that actual AnalysisOutcome is not success but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

}
