package io.quarkiverse.qubit.deployment.analysis;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link QueryCharacteristics} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractQueryCharacteristicsAssert<S extends AbstractQueryCharacteristicsAssert<S, A>, A extends QueryCharacteristics>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractQueryCharacteristicsAssert}</code> to make assertions on actual QueryCharacteristics.
     *
     * @param actual the QueryCharacteristics we want to make assertions on.
     */
    protected AbstractQueryCharacteristicsAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual QueryCharacteristics is aggregation query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not aggregation query.
     */
    public S isAggregationQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isAggregationQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is aggregation query but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not aggregation query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is aggregation query.
     */
    public S isNotAggregationQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isAggregationQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not aggregation query but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is count query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not count query.
     */
    public S isCountQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isCountQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is count query but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not count query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is count query.
     */
    public S isNotCountQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isCountQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not count query but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is group query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not group query.
     */
    public S isGroupQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isGroupQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is group query but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not group query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is group query.
     */
    public S isNotGroupQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isGroupQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not group query but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is join projection.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not join projection.
     */
    public S isJoinProjection() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isJoinProjection()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is join projection but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not join projection.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is join projection.
     */
    public S isNotJoinProjection() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isJoinProjection()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not join projection but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is join query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not join query.
     */
    public S isJoinQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isJoinQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is join query but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not join query.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is join query.
     */
    public S isNotJoinQuery() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isJoinQuery()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not join query but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is select joined.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is not select joined.
     */
    public S isSelectJoined() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isSelectJoined()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is select joined but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual QueryCharacteristics is not select joined.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual QueryCharacteristics is select joined.
     */
    public S isNotSelectJoined() {
        // check that actual QueryCharacteristics we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isSelectJoined()) {
            failWithMessage("\nExpecting that actual QueryCharacteristics is not select joined but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

}
