package io.quarkiverse.qubit.deployment.analysis;

/**
 * {@link AnalysisOutcome} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractAnalysisOutcomeAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class AnalysisOutcomeAssert extends AbstractAnalysisOutcomeAssert<AnalysisOutcomeAssert, AnalysisOutcome> {

    /**
     * Creates a new <code>{@link AnalysisOutcomeAssert}</code> to make assertions on actual AnalysisOutcome.
     *
     * @param actual the AnalysisOutcome we want to make assertions on.
     */
    public AnalysisOutcomeAssert(AnalysisOutcome actual) {
        super(actual, AnalysisOutcomeAssert.class);
    }

    /**
     * An entry point for AnalysisOutcomeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myAnalysisOutcome)</code> and get specific assertion with
     * code completion.
     *
     * @param actual the AnalysisOutcome we want to make assertions on.
     * @return a new <code>{@link AnalysisOutcomeAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static AnalysisOutcomeAssert assertThat(AnalysisOutcome actual) {
        return new AnalysisOutcomeAssert(actual);
    }
}
