package io.quarkiverse.qubit.deployment.analysis;

/**
 * {@link MethodScanState} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMethodScanStateAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class MethodScanStateAssert extends AbstractMethodScanStateAssert<MethodScanStateAssert, MethodScanState> {

    /**
     * Creates a new <code>{@link MethodScanStateAssert}</code> to make assertions on actual MethodScanState.
     *
     * @param actual the MethodScanState we want to make assertions on.
     */
    public MethodScanStateAssert(MethodScanState actual) {
        super(actual, MethodScanStateAssert.class);
    }

    /**
     * An entry point for MethodScanStateAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myMethodScanState)</code> and get specific assertion with
     * code completion.
     *
     * @param actual the MethodScanState we want to make assertions on.
     * @return a new <code>{@link MethodScanStateAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static MethodScanStateAssert assertThat(MethodScanState actual) {
        return new MethodScanStateAssert(actual);
    }
}
