package io.quarkiverse.qubit.deployment.analysis;

/**
 * {@link QueryExecutionPlan} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractQueryExecutionPlanAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class QueryExecutionPlanAssert extends AbstractQueryExecutionPlanAssert<QueryExecutionPlanAssert, QueryExecutionPlan> {

    /**
     * Creates a new <code>{@link QueryExecutionPlanAssert}</code> to make assertions on actual QueryExecutionPlan.
     *
     * @param actual the QueryExecutionPlan we want to make assertions on.
     */
    public QueryExecutionPlanAssert(QueryExecutionPlan actual) {
        super(actual, QueryExecutionPlanAssert.class);
    }

    /**
     * An entry point for QueryExecutionPlanAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myQueryExecutionPlan)</code> and get specific assertion
     * with code completion.
     *
     * @param actual the QueryExecutionPlan we want to make assertions on.
     * @return a new <code>{@link QueryExecutionPlanAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static QueryExecutionPlanAssert assertThat(QueryExecutionPlan actual) {
        return new QueryExecutionPlanAssert(actual);
    }
}
