package io.quarkiverse.qubit.deployment.analysis;

/**
 * {@link QueryCharacteristics} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractQueryCharacteristicsAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class QueryCharacteristicsAssert
        extends AbstractQueryCharacteristicsAssert<QueryCharacteristicsAssert, QueryCharacteristics> {

    /**
     * Creates a new <code>{@link QueryCharacteristicsAssert}</code> to make assertions on actual QueryCharacteristics.
     *
     * @param actual the QueryCharacteristics we want to make assertions on.
     */
    public QueryCharacteristicsAssert(QueryCharacteristics actual) {
        super(actual, QueryCharacteristicsAssert.class);
    }

    /**
     * An entry point for QueryCharacteristicsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myQueryCharacteristics)</code> and get specific assertion
     * with code completion.
     *
     * @param actual the QueryCharacteristics we want to make assertions on.
     * @return a new <code>{@link QueryCharacteristicsAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static QueryCharacteristicsAssert assertThat(QueryCharacteristics actual) {
        return new QueryCharacteristicsAssert(actual);
    }
}
