package io.quarkiverse.qubit.deployment.util;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link ByteArrayClassOutput}.
 *
 * <p>Tests the ClassOutput implementation that captures generated bytecode.
 */
class ByteArrayClassOutputTest {

    private ByteArrayClassOutput classOutput;

    @BeforeEach
    void setUp() {
        classOutput = new ByteArrayClassOutput();
    }

    // ==================== Initial State Tests ====================

    @Nested
    class InitialStateTests {

        @Test
        void getData_beforeWrite_returnsNull() {
            assertThat(classOutput.getData())
                    .as("Before write, data should be null")
                    .isNull();
        }
    }

    // ==================== write Tests ====================

    @Nested
    class WriteTests {

        @Test
        void write_withData_storesData() {
            byte[] testData = {0x01, 0x02, 0x03};

            classOutput.write("TestClass", testData);

            assertThat(classOutput.getData())
                    .as("Data should be stored after write")
                    .isEqualTo(testData);
        }

        @Test
        void write_withEmptyData_storesEmptyArray() {
            byte[] emptyData = new byte[0];

            classOutput.write("EmptyClass", emptyData);

            assertThat(classOutput.getData())
                    .as("Empty data should be stored")
                    .isEmpty();
        }

        @Test
        void write_withNullData_storesNull() {
            classOutput.write("NullClass", null);

            assertThat(classOutput.getData())
                    .as("Null data should be stored")
                    .isNull();
        }

        @Test
        void write_multipleTimes_storesLastData() {
            byte[] firstData = {0x01, 0x02};
            byte[] secondData = {0x03, 0x04, 0x05};

            classOutput.write("FirstClass", firstData);
            classOutput.write("SecondClass", secondData);

            assertThat(classOutput.getData())
                    .as("Last written data should be stored")
                    .isEqualTo(secondData);
        }

        @Test
        void write_withLargeData_storesAllBytes() {
            byte[] largeData = new byte[10000];
            for (int i = 0; i < largeData.length; i++) {
                largeData[i] = (byte) (i % 256);
            }

            classOutput.write("LargeClass", largeData);

            assertThat(classOutput.getData())
                    .as("Large data should be stored completely")
                    .hasSize(10000)
                    .isEqualTo(largeData);
        }

        @Test
        void write_ignoresClassName() {
            byte[] data = {0x01};

            classOutput.write("com.example.TestClass", data);

            assertThat(classOutput.getData())
                    .as("Class name is ignored, only data is stored")
                    .isEqualTo(data);
        }
    }

    // ==================== getData Tests ====================

    @Nested
    class GetDataTests {

        @Test
        void getData_returnsSameReference() {
            byte[] testData = {0x01, 0x02, 0x03};
            classOutput.write("Test", testData);

            byte[] firstCall = classOutput.getData();
            byte[] secondCall = classOutput.getData();

            assertThat(firstCall)
                    .as("Multiple calls should return same reference")
                    .isSameAs(secondCall);
        }

        @Test
        void getData_afterWrite_returnsSameArrayReference() {
            byte[] testData = {0x01, 0x02, 0x03};
            classOutput.write("Test", testData);

            assertThat(classOutput.getData())
                    .as("Should return the exact array passed to write")
                    .isSameAs(testData);
        }
    }
}
