package io.quarkiverse.qubit.deployment.metrics;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.api.Assertions;

/**
 * Abstract base class for {@link BuildMetricsCollector} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractBuildMetricsCollectorAssert<S extends AbstractBuildMetricsCollectorAssert<S, A>, A extends BuildMetricsCollector>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractBuildMetricsCollectorAssert}</code> to make assertions on actual
     * BuildMetricsCollector.
     *
     * @param actual the BuildMetricsCollector we want to make assertions on.
     */
    protected AbstractBuildMetricsCollectorAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual BuildMetricsCollector's activeThreadCount is equal to the given one.
     *
     * @param activeThreadCount the given activeThreadCount to compare the actual BuildMetricsCollector's activeThreadCount to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's activeThreadCount is not equal to the given one.
     */
    public S hasActiveThreadCount(int activeThreadCount) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting activeThreadCount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualActiveThreadCount = actual.getActiveThreadCount();
        if (actualActiveThreadCount != activeThreadCount) {
            failWithMessage(assertjErrorMessage, actual, activeThreadCount, actualActiveThreadCount);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's bytecodeCacheHitRate is equal to the given one.
     *
     * @param bytecodeCacheHitRate the given bytecodeCacheHitRate to compare the actual BuildMetricsCollector's
     *        bytecodeCacheHitRate to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's bytecodeCacheHitRate is not equal to the given one.
     */
    public S hasBytecodeCacheHitRate(double bytecodeCacheHitRate) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting bytecodeCacheHitRate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check value for bytecodeCacheHitRate
        double actualBytecodeCacheHitRate = actual.getBytecodeCacheHitRate();
        if (actualBytecodeCacheHitRate != bytecodeCacheHitRate) {
            failWithMessage(assertjErrorMessage, actual, bytecodeCacheHitRate, actualBytecodeCacheHitRate);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's bytecodeCacheHitRate is close to the given value by less than the given
     * offset.
     * <p>
     * If difference is equal to the offset value, assertion is considered successful.
     *
     * @param bytecodeCacheHitRate the value to compare the actual BuildMetricsCollector's bytecodeCacheHitRate to.
     * @param assertjOffset the given offset.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's bytecodeCacheHitRate is not close enough to the given
     *         value.
     */
    public S hasBytecodeCacheHitRateCloseTo(double bytecodeCacheHitRate, double assertjOffset) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        double actualBytecodeCacheHitRate = actual.getBytecodeCacheHitRate();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = String.format(
                "\nExpecting bytecodeCacheHitRate:\n  <%s>\nto be close to:\n  <%s>\nby less than <%s> but difference was <%s>",
                actualBytecodeCacheHitRate, bytecodeCacheHitRate, assertjOffset,
                Math.abs(bytecodeCacheHitRate - actualBytecodeCacheHitRate));

        // check
        Assertions.assertThat(actualBytecodeCacheHitRate).overridingErrorMessage(assertjErrorMessage)
                .isCloseTo(bytecodeCacheHitRate, Assertions.within(assertjOffset));

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's bytecodeLoadTimeNanos is equal to the given one.
     *
     * @param bytecodeLoadTimeNanos the given bytecodeLoadTimeNanos to compare the actual BuildMetricsCollector's
     *        bytecodeLoadTimeNanos to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's bytecodeLoadTimeNanos is not equal to the given one.
     */
    public S hasBytecodeLoadTimeNanos(long bytecodeLoadTimeNanos) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting bytecodeLoadTimeNanos of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualBytecodeLoadTimeNanos = actual.getBytecodeLoadTimeNanos();
        if (actualBytecodeLoadTimeNanos != bytecodeLoadTimeNanos) {
            failWithMessage(assertjErrorMessage, actual, bytecodeLoadTimeNanos, actualBytecodeLoadTimeNanos);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's classNodeCacheHitRate is equal to the given one.
     *
     * @param classNodeCacheHitRate the given classNodeCacheHitRate to compare the actual BuildMetricsCollector's
     *        classNodeCacheHitRate to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's classNodeCacheHitRate is not equal to the given one.
     */
    public S hasClassNodeCacheHitRate(double classNodeCacheHitRate) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting classNodeCacheHitRate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check value for classNodeCacheHitRate
        double actualClassNodeCacheHitRate = actual.getClassNodeCacheHitRate();
        if (actualClassNodeCacheHitRate != classNodeCacheHitRate) {
            failWithMessage(assertjErrorMessage, actual, classNodeCacheHitRate, actualClassNodeCacheHitRate);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's classNodeCacheHitRate is close to the given value by less than the given
     * offset.
     * <p>
     * If difference is equal to the offset value, assertion is considered successful.
     *
     * @param classNodeCacheHitRate the value to compare the actual BuildMetricsCollector's classNodeCacheHitRate to.
     * @param assertjOffset the given offset.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's classNodeCacheHitRate is not close enough to the given
     *         value.
     */
    public S hasClassNodeCacheHitRateCloseTo(double classNodeCacheHitRate, double assertjOffset) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        double actualClassNodeCacheHitRate = actual.getClassNodeCacheHitRate();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = String.format(
                "\nExpecting classNodeCacheHitRate:\n  <%s>\nto be close to:\n  <%s>\nby less than <%s> but difference was <%s>",
                actualClassNodeCacheHitRate, classNodeCacheHitRate, assertjOffset,
                Math.abs(classNodeCacheHitRate - actualClassNodeCacheHitRate));

        // check
        Assertions.assertThat(actualClassNodeCacheHitRate).overridingErrorMessage(assertjErrorMessage)
                .isCloseTo(classNodeCacheHitRate, Assertions.within(assertjOffset));

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's classesScanned is equal to the given one.
     *
     * @param classesScanned the given classesScanned to compare the actual BuildMetricsCollector's classesScanned to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's classesScanned is not equal to the given one.
     */
    public S hasClassesScanned(long classesScanned) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting classesScanned of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualClassesScanned = actual.getClassesScanned();
        if (actualClassesScanned != classesScanned) {
            failWithMessage(assertjErrorMessage, actual, classesScanned, actualClassesScanned);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's codeGenCacheHitRate is equal to the given one.
     *
     * @param codeGenCacheHitRate the given codeGenCacheHitRate to compare the actual BuildMetricsCollector's
     *        codeGenCacheHitRate to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's codeGenCacheHitRate is not equal to the given one.
     */
    public S hasCodeGenCacheHitRate(double codeGenCacheHitRate) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting codeGenCacheHitRate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check value for codeGenCacheHitRate
        double actualCodeGenCacheHitRate = actual.getCodeGenCacheHitRate();
        if (actualCodeGenCacheHitRate != codeGenCacheHitRate) {
            failWithMessage(assertjErrorMessage, actual, codeGenCacheHitRate, actualCodeGenCacheHitRate);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's codeGenCacheHitRate is close to the given value by less than the given
     * offset.
     * <p>
     * If difference is equal to the offset value, assertion is considered successful.
     *
     * @param codeGenCacheHitRate the value to compare the actual BuildMetricsCollector's codeGenCacheHitRate to.
     * @param assertjOffset the given offset.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's codeGenCacheHitRate is not close enough to the given
     *         value.
     */
    public S hasCodeGenCacheHitRateCloseTo(double codeGenCacheHitRate, double assertjOffset) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        double actualCodeGenCacheHitRate = actual.getCodeGenCacheHitRate();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = String.format(
                "\nExpecting codeGenCacheHitRate:\n  <%s>\nto be close to:\n  <%s>\nby less than <%s> but difference was <%s>",
                actualCodeGenCacheHitRate, codeGenCacheHitRate, assertjOffset,
                Math.abs(codeGenCacheHitRate - actualCodeGenCacheHitRate));

        // check
        Assertions.assertThat(actualCodeGenCacheHitRate).overridingErrorMessage(assertjErrorMessage)
                .isCloseTo(codeGenCacheHitRate, Assertions.within(assertjOffset));

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's codeGenCacheHits is equal to the given one.
     *
     * @param codeGenCacheHits the given codeGenCacheHits to compare the actual BuildMetricsCollector's codeGenCacheHits to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's codeGenCacheHits is not equal to the given one.
     */
    public S hasCodeGenCacheHits(long codeGenCacheHits) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting codeGenCacheHits of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualCodeGenCacheHits = actual.getCodeGenCacheHits();
        if (actualCodeGenCacheHits != codeGenCacheHits) {
            failWithMessage(assertjErrorMessage, actual, codeGenCacheHits, actualCodeGenCacheHits);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's codeGenCacheMisses is equal to the given one.
     *
     * @param codeGenCacheMisses the given codeGenCacheMisses to compare the actual BuildMetricsCollector's codeGenCacheMisses
     *        to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's codeGenCacheMisses is not equal to the given one.
     */
    public S hasCodeGenCacheMisses(long codeGenCacheMisses) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting codeGenCacheMisses of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualCodeGenCacheMisses = actual.getCodeGenCacheMisses();
        if (actualCodeGenCacheMisses != codeGenCacheMisses) {
            failWithMessage(assertjErrorMessage, actual, codeGenCacheMisses, actualCodeGenCacheMisses);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's codeGenerationTimeNanos is equal to the given one.
     *
     * @param codeGenerationTimeNanos the given codeGenerationTimeNanos to compare the actual BuildMetricsCollector's
     *        codeGenerationTimeNanos to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's codeGenerationTimeNanos is not equal to the given one.
     */
    public S hasCodeGenerationTimeNanos(long codeGenerationTimeNanos) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting codeGenerationTimeNanos of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualCodeGenerationTimeNanos = actual.getCodeGenerationTimeNanos();
        if (actualCodeGenerationTimeNanos != codeGenerationTimeNanos) {
            failWithMessage(assertjErrorMessage, actual, codeGenerationTimeNanos, actualCodeGenerationTimeNanos);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's duplicateCount is equal to the given one.
     *
     * @param duplicateCount the given duplicateCount to compare the actual BuildMetricsCollector's duplicateCount to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's duplicateCount is not equal to the given one.
     */
    public S hasDuplicateCount(long duplicateCount) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting duplicateCount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualDuplicateCount = actual.getDuplicateCount();
        if (actualDuplicateCount != duplicateCount) {
            failWithMessage(assertjErrorMessage, actual, duplicateCount, actualDuplicateCount);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's earlyDeduplicationCheckTimeNanos is equal to the given one.
     *
     * @param earlyDeduplicationCheckTimeNanos the given earlyDeduplicationCheckTimeNanos to compare the actual
     *        BuildMetricsCollector's earlyDeduplicationCheckTimeNanos to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's earlyDeduplicationCheckTimeNanos is not equal to the given
     *         one.
     */
    public S hasEarlyDeduplicationCheckTimeNanos(long earlyDeduplicationCheckTimeNanos) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting earlyDeduplicationCheckTimeNanos of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualEarlyDeduplicationCheckTimeNanos = actual.getEarlyDeduplicationCheckTimeNanos();
        if (actualEarlyDeduplicationCheckTimeNanos != earlyDeduplicationCheckTimeNanos) {
            failWithMessage(assertjErrorMessage, actual, earlyDeduplicationCheckTimeNanos,
                    actualEarlyDeduplicationCheckTimeNanos);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's earlyDeduplicationHits is equal to the given one.
     *
     * @param earlyDeduplicationHits the given earlyDeduplicationHits to compare the actual BuildMetricsCollector's
     *        earlyDeduplicationHits to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's earlyDeduplicationHits is not equal to the given one.
     */
    public S hasEarlyDeduplicationHits(long earlyDeduplicationHits) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting earlyDeduplicationHits of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualEarlyDeduplicationHits = actual.getEarlyDeduplicationHits();
        if (actualEarlyDeduplicationHits != earlyDeduplicationHits) {
            failWithMessage(assertjErrorMessage, actual, earlyDeduplicationHits, actualEarlyDeduplicationHits);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's entityClassesEnhanced is equal to the given one.
     *
     * @param entityClassesEnhanced the given entityClassesEnhanced to compare the actual BuildMetricsCollector's
     *        entityClassesEnhanced to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's entityClassesEnhanced is not equal to the given one.
     */
    public S hasEntityClassesEnhanced(int entityClassesEnhanced) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting entityClassesEnhanced of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualEntityClassesEnhanced = actual.getEntityClassesEnhanced();
        if (actualEntityClassesEnhanced != entityClassesEnhanced) {
            failWithMessage(assertjErrorMessage, actual, entityClassesEnhanced, actualEntityClassesEnhanced);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's instructionAnalysisTimeNanos is equal to the given one.
     *
     * @param instructionAnalysisTimeNanos the given instructionAnalysisTimeNanos to compare the actual BuildMetricsCollector's
     *        instructionAnalysisTimeNanos to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's instructionAnalysisTimeNanos is not equal to the given
     *         one.
     */
    public S hasInstructionAnalysisTimeNanos(long instructionAnalysisTimeNanos) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting instructionAnalysisTimeNanos of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualInstructionAnalysisTimeNanos = actual.getInstructionAnalysisTimeNanos();
        if (actualInstructionAnalysisTimeNanos != instructionAnalysisTimeNanos) {
            failWithMessage(assertjErrorMessage, actual, instructionAnalysisTimeNanos, actualInstructionAnalysisTimeNanos);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's jandexPreFilterSkips is equal to the given one.
     *
     * @param jandexPreFilterSkips the given jandexPreFilterSkips to compare the actual BuildMetricsCollector's
     *        jandexPreFilterSkips to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's jandexPreFilterSkips is not equal to the given one.
     */
    public S hasJandexPreFilterSkips(long jandexPreFilterSkips) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting jandexPreFilterSkips of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualJandexPreFilterSkips = actual.getJandexPreFilterSkips();
        if (actualJandexPreFilterSkips != jandexPreFilterSkips) {
            failWithMessage(assertjErrorMessage, actual, jandexPreFilterSkips, actualJandexPreFilterSkips);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's queryCount is equal to the given one.
     *
     * @param queryCount the given queryCount to compare the actual BuildMetricsCollector's queryCount to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's queryCount is not equal to the given one.
     */
    public S hasQueryCount(int queryCount) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting queryCount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualQueryCount = actual.getQueryCount();
        if (actualQueryCount != queryCount) {
            failWithMessage(assertjErrorMessage, actual, queryCount, actualQueryCount);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's quickCheckPasses is equal to the given one.
     *
     * @param quickCheckPasses the given quickCheckPasses to compare the actual BuildMetricsCollector's quickCheckPasses to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's quickCheckPasses is not equal to the given one.
     */
    public S hasQuickCheckPasses(long quickCheckPasses) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting quickCheckPasses of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualQuickCheckPasses = actual.getQuickCheckPasses();
        if (actualQuickCheckPasses != quickCheckPasses) {
            failWithMessage(assertjErrorMessage, actual, quickCheckPasses, actualQuickCheckPasses);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's quickCheckSkipRate is equal to the given one.
     *
     * @param quickCheckSkipRate the given quickCheckSkipRate to compare the actual BuildMetricsCollector's quickCheckSkipRate
     *        to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's quickCheckSkipRate is not equal to the given one.
     */
    public S hasQuickCheckSkipRate(double quickCheckSkipRate) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting quickCheckSkipRate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check value for quickCheckSkipRate
        double actualQuickCheckSkipRate = actual.getQuickCheckSkipRate();
        if (actualQuickCheckSkipRate != quickCheckSkipRate) {
            failWithMessage(assertjErrorMessage, actual, quickCheckSkipRate, actualQuickCheckSkipRate);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's quickCheckSkipRate is close to the given value by less than the given
     * offset.
     * <p>
     * If difference is equal to the offset value, assertion is considered successful.
     *
     * @param quickCheckSkipRate the value to compare the actual BuildMetricsCollector's quickCheckSkipRate to.
     * @param assertjOffset the given offset.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's quickCheckSkipRate is not close enough to the given value.
     */
    public S hasQuickCheckSkipRateCloseTo(double quickCheckSkipRate, double assertjOffset) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        double actualQuickCheckSkipRate = actual.getQuickCheckSkipRate();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = String.format(
                "\nExpecting quickCheckSkipRate:\n  <%s>\nto be close to:\n  <%s>\nby less than <%s> but difference was <%s>",
                actualQuickCheckSkipRate, quickCheckSkipRate, assertjOffset,
                Math.abs(quickCheckSkipRate - actualQuickCheckSkipRate));

        // check
        Assertions.assertThat(actualQuickCheckSkipRate).overridingErrorMessage(assertjErrorMessage)
                .isCloseTo(quickCheckSkipRate, Assertions.within(assertjOffset));

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's quickCheckSkips is equal to the given one.
     *
     * @param quickCheckSkips the given quickCheckSkips to compare the actual BuildMetricsCollector's quickCheckSkips to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's quickCheckSkips is not equal to the given one.
     */
    public S hasQuickCheckSkips(long quickCheckSkips) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting quickCheckSkips of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualQuickCheckSkips = actual.getQuickCheckSkips();
        if (actualQuickCheckSkips != quickCheckSkips) {
            failWithMessage(assertjErrorMessage, actual, quickCheckSkips, actualQuickCheckSkips);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's repositoriesEnhanced is equal to the given one.
     *
     * @param repositoriesEnhanced the given repositoriesEnhanced to compare the actual BuildMetricsCollector's
     *        repositoriesEnhanced to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's repositoriesEnhanced is not equal to the given one.
     */
    public S hasRepositoriesEnhanced(int repositoriesEnhanced) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting repositoriesEnhanced of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualRepositoriesEnhanced = actual.getRepositoriesEnhanced();
        if (actualRepositoriesEnhanced != repositoriesEnhanced) {
            failWithMessage(assertjErrorMessage, actual, repositoriesEnhanced, actualRepositoriesEnhanced);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's totalBytecodeLoads is equal to the given one.
     *
     * @param totalBytecodeLoads the given totalBytecodeLoads to compare the actual BuildMetricsCollector's totalBytecodeLoads
     *        to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's totalBytecodeLoads is not equal to the given one.
     */
    public S hasTotalBytecodeLoads(long totalBytecodeLoads) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting totalBytecodeLoads of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualTotalBytecodeLoads = actual.getTotalBytecodeLoads();
        if (actualTotalBytecodeLoads != totalBytecodeLoads) {
            failWithMessage(assertjErrorMessage, actual, totalBytecodeLoads, actualTotalBytecodeLoads);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual BuildMetricsCollector's uniqueClassesLoaded is equal to the given one.
     *
     * @param uniqueClassesLoaded the given uniqueClassesLoaded to compare the actual BuildMetricsCollector's
     *        uniqueClassesLoaded to.
     * @return this assertion object.
     * @throws AssertionError - if the actual BuildMetricsCollector's uniqueClassesLoaded is not equal to the given one.
     */
    public S hasUniqueClassesLoaded(long uniqueClassesLoaded) {
        // check that actual BuildMetricsCollector we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting uniqueClassesLoaded of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        long actualUniqueClassesLoaded = actual.getUniqueClassesLoaded();
        if (actualUniqueClassesLoaded != uniqueClassesLoaded) {
            failWithMessage(assertjErrorMessage, actual, uniqueClassesLoaded, actualUniqueClassesLoaded);
        }

        // return the current assertion for method chaining
        return myself;
    }

}
