package io.quarkiverse.qubit.deployment.metrics;

/**
 * {@link BuildMetricsCollector} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractBuildMetricsCollectorAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class BuildMetricsCollectorAssert
        extends AbstractBuildMetricsCollectorAssert<BuildMetricsCollectorAssert, BuildMetricsCollector> {

    /**
     * Creates a new <code>{@link BuildMetricsCollectorAssert}</code> to make assertions on actual BuildMetricsCollector.
     *
     * @param actual the BuildMetricsCollector we want to make assertions on.
     */
    public BuildMetricsCollectorAssert(BuildMetricsCollector actual) {
        super(actual, BuildMetricsCollectorAssert.class);
    }

    /**
     * An entry point for BuildMetricsCollectorAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myBuildMetricsCollector)</code> and get specific assertion
     * with code completion.
     *
     * @param actual the BuildMetricsCollector we want to make assertions on.
     * @return a new <code>{@link BuildMetricsCollectorAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static BuildMetricsCollectorAssert assertThat(BuildMetricsCollector actual) {
        return new BuildMetricsCollectorAssert(actual);
    }
}
