package io.quarkiverse.qubit.deployment;

import io.quarkiverse.qubit.deployment.analysis.CapturedVariableHelper;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

import static io.quarkiverse.qubit.deployment.testutil.AstBuilders.*;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests to verify missing coverage for Cast, InstanceOf, and Conditional expression types.
 *
 * <p>These tests document and verify that {@code collectCapturedVariableIndices()} does NOT
 * handle the following expression types:
 * <ul>
 *   <li>{@link LambdaExpression.Cast}</li>
 *   <li>{@link LambdaExpression.InstanceOf}</li>
 *   <li>{@link LambdaExpression.Conditional}</li>
 * </ul>
 *
 * <p>This is intentional because these expression types are:
 * <ol>
 *   <li>Never generated by the bytecode analyzer in production code</li>
 *   <li>Only exist in unit tests for the LambdaExpression data structures</li>
 *   <li>Not part of the supported query lambda syntax</li>
 * </ol>
 *
 * <p>These tests verify that IF these types were ever used in production (which they aren't),
 * any captured variables within them would be silently ignored, resulting in incorrect
 * captured variable counts.
 *
 * <p><strong>Context:</strong> The {@code containsCapturedVariables()} method was removed
 * because it was redundant (just checking {@code countCapturedVariables() > 0} provides the
 * same information). During removal, we identified that both methods had the same gap in
 * coverage for these three expression types. These tests document this gap and verify that
 * it exists as expected.
 *
 * <p>Uses {@link io.quarkiverse.qubit.deployment.testutil.AstBuilders} for fluent AST construction.
 */
class CapturedVariableCoverageTest {

    /**
     * Helper method to call collectCapturedVariableIndices from CapturedVariableHelper.
     */
    private Set<Integer> collectCapturedVariables(LambdaExpression expression) {
        Set<Integer> capturedIndices = new HashSet<>();
        CapturedVariableHelper.collectCapturedVariableIndices(expression, capturedIndices);
        return capturedIndices;
    }

    /**
     * Helper method to call countCapturedVariables from CapturedVariableHelper.
     */
    private int countCapturedVariables(LambdaExpression expression) {
        return CapturedVariableHelper.countCapturedVariables(expression);
    }

    // ========================================================================
    // Tests for Cast Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testCastExpression_withCapturedVariable_missesVariable() {
        // Create a Cast expression containing a captured variable
        // Pattern: (String) capturedVar
        var capturedVar = captured(0, Object.class);
        var castExpr = cast(capturedVar, String.class);

        // Verify that the captured variable is MISSED (not detected)
        Set<Integer> capturedIndices = collectCapturedVariables(castExpr);

        assertThat(capturedIndices)
                .as("Cast expression should NOT detect captured variables in its child expression")
                .isEmpty();
    }

    @Test
    void testCastExpression_withNestedCapturedVariable_missesVariable() {
        // Create a more complex Cast expression with nested captured variable
        // Pattern: (Integer) (capturedVar + 5)
        var capturedVar = captured(1, Integer.class);
        var addition = add(capturedVar, constant(5));
        var castExpr = cast(addition, Integer.class);

        // The BinaryOp would normally traverse its children, but since it's wrapped in Cast,
        // the Cast is the entry point and it doesn't traverse its child
        Set<Integer> capturedIndices = collectCapturedVariables(castExpr);

        assertThat(capturedIndices)
                .as("Cast expression should NOT detect captured variables even when nested in supported types")
                .isEmpty();
    }

    @Test
    void testCastExpression_countCapturedVariables_returnsZero() {
        // Verify that countCapturedVariables also misses variables in Cast expressions
        var capturedVar = captured(0, Object.class);
        var castExpr = cast(capturedVar, String.class);

        int count = countCapturedVariables(castExpr);

        assertThat(count)
                .as("countCapturedVariables should return 0 for Cast expressions")
                .isZero();
    }

    // ========================================================================
    // Tests for InstanceOf Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testInstanceOfExpression_withCapturedVariable_missesVariable() {
        // Create an InstanceOf expression containing a captured variable
        // Pattern: capturedVar instanceof String
        var capturedVar = captured(0, Object.class);
        var instanceOfExpr = instanceOf(capturedVar, String.class);

        // Verify that the captured variable is MISSED (not detected)
        Set<Integer> capturedIndices = collectCapturedVariables(instanceOfExpr);

        assertThat(capturedIndices)
                .as("InstanceOf expression should NOT detect captured variables in its child expression")
                .isEmpty();
    }

    @Test
    void testInstanceOfExpression_withComplexChild_missesVariable() {
        // Create an InstanceOf expression with a method call containing captured variable
        // Pattern: capturedVar.getValue() instanceof String
        var capturedVar = captured(2, Object.class);
        var methodCallExpr = methodCall(capturedVar, "getValue", Object.class);
        var instanceOfExpr = instanceOf(methodCallExpr, String.class);

        // The MethodCall would normally traverse its target, but since it's wrapped in InstanceOf,
        // the InstanceOf is the entry point and it doesn't traverse its child
        Set<Integer> capturedIndices = collectCapturedVariables(instanceOfExpr);

        assertThat(capturedIndices)
                .as("InstanceOf expression should NOT detect captured variables even in complex child expressions")
                .isEmpty();
    }

    @Test
    void testInstanceOfExpression_countCapturedVariables_returnsZero() {
        // Verify that countCapturedVariables also misses variables in InstanceOf expressions
        var capturedVar = captured(0, Object.class);
        var instanceOfExpr = instanceOf(capturedVar, String.class);

        int count = countCapturedVariables(instanceOfExpr);

        assertThat(count)
                .as("countCapturedVariables should return 0 for InstanceOf expressions")
                .isZero();
    }

    // ========================================================================
    // Tests for Conditional Expression (Missing Coverage)
    // ========================================================================

    @Test
    void testConditionalExpression_withCapturedVariableInCondition_missesVariable() {
        // Create a Conditional expression with captured variable in condition
        // Pattern: capturedFlag ? "yes" : "no"
        var capturedVar = captured(0, Boolean.class);
        var trueValue = constant("yes");
        var falseValue = constant("no");
        var conditionalExpr = conditional(capturedVar, trueValue, falseValue);

        // Verify that the captured variable in condition is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditionalExpr);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in condition")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withCapturedVariableInTrueValue_missesVariable() {
        // Create a Conditional expression with captured variable in true value
        // Pattern: active ? capturedName : "Unknown"
        var condition = field("active", Boolean.class);
        var capturedVar = captured(1, String.class);
        var falseValue = constant("Unknown");
        var conditionalExpr = conditional(condition, capturedVar, falseValue);

        // Verify that the captured variable in true value is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditionalExpr);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in true value")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withCapturedVariableInFalseValue_missesVariable() {
        // Create a Conditional expression with captured variable in false value
        // Pattern: active ? "Active" : capturedStatus
        var condition = field("active", Boolean.class);
        var trueValue = constant("Active");
        var capturedVar = captured(2, String.class);
        var conditionalExpr = conditional(condition, trueValue, capturedVar);

        // Verify that the captured variable in false value is MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditionalExpr);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in false value")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_withMultipleCapturedVariables_missesAll() {
        // Create a Conditional expression with captured variables in all three positions
        // Pattern: capturedFlag ? capturedName : capturedDefault
        var capturedCondition = captured(0, Boolean.class);
        var capturedTrue = captured(1, String.class);
        var capturedFalse = captured(2, String.class);
        var conditionalExpr = conditional(capturedCondition, capturedTrue, capturedFalse);

        // Verify that ALL three captured variables are MISSED
        Set<Integer> capturedIndices = collectCapturedVariables(conditionalExpr);

        assertThat(capturedIndices)
                .as("Conditional expression should NOT detect captured variables in any position")
                .isEmpty();
    }

    @Test
    void testConditionalExpression_countCapturedVariables_returnsZero() {
        // Verify that countCapturedVariables also misses variables in Conditional expressions
        var capturedVar = captured(0, Boolean.class);
        var trueValue = constant("yes");
        var falseValue = constant("no");
        var conditionalExpr = conditional(capturedVar, trueValue, falseValue);

        int count = countCapturedVariables(conditionalExpr);

        assertThat(count)
                .as("countCapturedVariables should return 0 for Conditional expressions")
                .isZero();
    }

    // ========================================================================
    // Baseline Tests (Verify that supported types DO detect variables)
    // ========================================================================

    @Test
    void testSupportedTypes_detectCapturedVariables() {
        // Verify that the supported expression types DO correctly detect captured variables
        // This serves as a baseline to confirm the test methodology is correct

        // Test BinaryOp (supported)
        var capturedVar1 = captured(0, Integer.class);
        var binaryOp = gt(capturedVar1, constant(5));

        assertThat(collectCapturedVariables(binaryOp))
                .as("BinaryOp should correctly detect captured variables")
                .containsExactly(0);

        // Test UnaryOp (supported)
        var capturedVar2 = captured(1, Boolean.class);
        var unaryOp = not(capturedVar2);

        assertThat(collectCapturedVariables(unaryOp))
                .as("UnaryOp should correctly detect captured variables")
                .containsExactly(1);

        // Test MethodCall (supported)
        var capturedVar3 = captured(2, String.class);
        var methodCallExpr = methodCall(capturedVar3, "toLowerCase", String.class);

        assertThat(collectCapturedVariables(methodCallExpr))
                .as("MethodCall should correctly detect captured variables in target")
                .containsExactly(2);
    }

    @Test
    void testDirectCapturedVariable_isDetected() {
        // Verify that a direct CapturedVariable is always detected
        var capturedVar = captured(5, String.class);

        assertThat(collectCapturedVariables(capturedVar))
                .as("Direct CapturedVariable should be detected")
                .containsExactly(5);

        assertThat(countCapturedVariables(capturedVar))
                .as("countCapturedVariables should return 1 for direct CapturedVariable")
                .isEqualTo(1);
    }
}
