package io.quarkiverse.qubit.deployment.analysis.instruction;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link AnalysisContext} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractAnalysisContextAssert<S extends AbstractAnalysisContextAssert<S, A>, A extends AnalysisContext>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractAnalysisContextAssert}</code> to make assertions on actual AnalysisContext.
     *
     * @param actual the AnalysisContext we want to make assertions on.
     */
    protected AbstractAnalysisContextAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual AnalysisContext is bi entity mode.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is not bi entity mode.
     */
    public S isBiEntityMode() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isBiEntityMode()) {
            failWithMessage("\nExpecting that actual AnalysisContext is bi entity mode but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is not bi entity mode.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is bi entity mode.
     */
    public S isNotBiEntityMode() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isBiEntityMode()) {
            failWithMessage("\nExpecting that actual AnalysisContext is not bi entity mode but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's branchCoordinator is equal to the given one.
     *
     * @param branchCoordinator the given branchCoordinator to compare the actual AnalysisContext's branchCoordinator to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's branchCoordinator is not equal to the given one.
     */
    public S hasBranchCoordinator(io.quarkiverse.qubit.deployment.analysis.branch.BranchCoordinator branchCoordinator) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting branchCoordinator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        io.quarkiverse.qubit.deployment.analysis.branch.BranchCoordinator actualBranchCoordinator = actual
                .getBranchCoordinator();
        if (!Objects.areEqual(actualBranchCoordinator, branchCoordinator)) {
            failWithMessage(assertjErrorMessage, actual, branchCoordinator, actualBranchCoordinator);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's currentInstructionIndex is equal to the given one.
     *
     * @param currentInstructionIndex the given currentInstructionIndex to compare the actual AnalysisContext's
     *        currentInstructionIndex to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's currentInstructionIndex is not equal to the given one.
     */
    public S hasCurrentInstructionIndex(int currentInstructionIndex) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting currentInstructionIndex of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualCurrentInstructionIndex = actual.getCurrentInstructionIndex();
        if (actualCurrentInstructionIndex != currentInstructionIndex) {
            failWithMessage(assertjErrorMessage, actual, currentInstructionIndex, actualCurrentInstructionIndex);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's firstEntityParameterIndex is equal to the given one.
     *
     * @param firstEntityParameterIndex the given firstEntityParameterIndex to compare the actual AnalysisContext's
     *        firstEntityParameterIndex to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's firstEntityParameterIndex is not equal to the given one.
     */
    public S hasFirstEntityParameterIndex(int firstEntityParameterIndex) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting firstEntityParameterIndex of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualFirstEntityParameterIndex = actual.getFirstEntityParameterIndex();
        if (actualFirstEntityParameterIndex != firstEntityParameterIndex) {
            failWithMessage(assertjErrorMessage, actual, firstEntityParameterIndex, actualFirstEntityParameterIndex);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is group context mode.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is not group context mode.
     */
    public S isGroupContextMode() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isGroupContextMode()) {
            failWithMessage("\nExpecting that actual AnalysisContext is group context mode but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is not group context mode.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is group context mode.
     */
    public S isNotGroupContextMode() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isGroupContextMode()) {
            failWithMessage("\nExpecting that actual AnalysisContext is not group context mode but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is in array creation.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is not in array creation.
     */
    public S isInArrayCreation() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isInArrayCreation()) {
            failWithMessage("\nExpecting that actual AnalysisContext is in array creation but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is not in array creation.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is in array creation.
     */
    public S isNotInArrayCreation() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isInArrayCreation()) {
            failWithMessage("\nExpecting that actual AnalysisContext is not in array creation but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructionCount is equal to the given one.
     *
     * @param instructionCount the given instructionCount to compare the actual AnalysisContext's instructionCount to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's instructionCount is not equal to the given one.
     */
    public S hasInstructionCount(int instructionCount) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting instructionCount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualInstructionCount = actual.getInstructionCount();
        if (actualInstructionCount != instructionCount) {
            failWithMessage(assertjErrorMessage, actual, instructionCount, actualInstructionCount);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions contains the given org.objectweb.asm.tree.AbstractInsnNode
     * elements.
     *
     * @param instructions the given elements that should be contained in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions does not contain all given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S hasInstructions(org.objectweb.asm.tree.AbstractInsnNode... instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode varargs is not null.
        if (instructions == null)
            failWithMessage("Expecting instructions parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getInstructions(), instructions);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions contains the given org.objectweb.asm.tree.AbstractInsnNode
     * elements in Collection.
     *
     * @param instructions the given elements that should be contained in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions does not contain all given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S hasInstructions(java.util.Collection<? extends org.objectweb.asm.tree.AbstractInsnNode> instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode collection is not null.
        if (instructions == null) {
            failWithMessage("Expecting instructions parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getInstructions(), instructions.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions contains <b>only</b> the given
     * org.objectweb.asm.tree.AbstractInsnNode elements and nothing else in whatever order.
     *
     * @param instructions the given elements that should be contained in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions does not contain all given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S hasOnlyInstructions(org.objectweb.asm.tree.AbstractInsnNode... instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode varargs is not null.
        if (instructions == null)
            failWithMessage("Expecting instructions parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getInstructions(), instructions);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions contains <b>only</b> the given
     * org.objectweb.asm.tree.AbstractInsnNode elements in Collection and nothing else in whatever order.
     *
     * @param instructions the given elements that should be contained in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions does not contain all given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S hasOnlyInstructions(java.util.Collection<? extends org.objectweb.asm.tree.AbstractInsnNode> instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode collection is not null.
        if (instructions == null) {
            failWithMessage("Expecting instructions parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getInstructions(), instructions.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions does not contain the given
     * org.objectweb.asm.tree.AbstractInsnNode elements.
     *
     * @param instructions the given elements that should not be in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions contains any given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S doesNotHaveInstructions(org.objectweb.asm.tree.AbstractInsnNode... instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode varargs is not null.
        if (instructions == null)
            failWithMessage("Expecting instructions parameter not to be null.");

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getInstructions(), instructions);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's instructions does not contain the given
     * org.objectweb.asm.tree.AbstractInsnNode elements in Collection.
     *
     * @param instructions the given elements that should not be in actual AnalysisContext's instructions.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions contains any given
     *         org.objectweb.asm.tree.AbstractInsnNode elements.
     */
    public S doesNotHaveInstructions(java.util.Collection<? extends org.objectweb.asm.tree.AbstractInsnNode> instructions) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given org.objectweb.asm.tree.AbstractInsnNode collection is not null.
        if (instructions == null) {
            failWithMessage("Expecting instructions parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getInstructions(), instructions.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has no instructions.
     *
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's instructions is not empty.
     */
    public S hasNoInstructions() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // we override the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have instructions but had :\n  <%s>";

        // check
        if (actual.getInstructions().iterator().hasNext()) {
            failWithMessage(assertjErrorMessage, actual, actual.getInstructions());
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's labelClassifications is equal to the given one.
     *
     * @param labelClassifications the given labelClassifications to compare the actual AnalysisContext's labelClassifications
     *        to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's labelClassifications is not equal to the given one.
     */
    public S hasLabelClassifications(java.util.Map labelClassifications) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting labelClassifications of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        java.util.Map actualLabelClassifications = actual.getLabelClassifications();
        if (!Objects.areEqual(actualLabelClassifications, labelClassifications)) {
            failWithMessage(assertjErrorMessage, actual, labelClassifications, actualLabelClassifications);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's labelToValue is equal to the given one.
     *
     * @param labelToValue the given labelToValue to compare the actual AnalysisContext's labelToValue to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's labelToValue is not equal to the given one.
     */
    public S hasLabelToValue(java.util.Map labelToValue) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting labelToValue of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        java.util.Map actualLabelToValue = actual.getLabelToValue();
        if (!Objects.areEqual(actualLabelToValue, labelToValue)) {
            failWithMessage(assertjErrorMessage, actual, labelToValue, actualLabelToValue);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's method is equal to the given one.
     *
     * @param method the given method to compare the actual AnalysisContext's method to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's method is not equal to the given one.
     */
    public S hasMethod(org.objectweb.asm.tree.MethodNode method) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting method of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        org.objectweb.asm.tree.MethodNode actualMethod = actual.getMethod();
        if (!Objects.areEqual(actualMethod, method)) {
            failWithMessage(assertjErrorMessage, actual, method, actualMethod);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has nested lambda support.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext does not have nested lambda support.
     */
    public S hasNestedLambdaSupport() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasNestedLambdaSupport()) {
            failWithMessage("\nExpecting that actual AnalysisContext has nested lambda support but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext does not have nested lambda support.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext has nested lambda support.
     */
    public S doesNotHaveNestedLambdaSupport() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasNestedLambdaSupport()) {
            failWithMessage("\nExpecting that actual AnalysisContext does not have nested lambda support but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElementType is equal to the given one.
     *
     * @param pendingArrayElementType the given pendingArrayElementType to compare the actual AnalysisContext's
     *        pendingArrayElementType to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's pendingArrayElementType is not equal to the given one.
     */
    public S hasPendingArrayElementType(String pendingArrayElementType) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting pendingArrayElementType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        String actualPendingArrayElementType = actual.getPendingArrayElementType();
        if (!Objects.areEqual(actualPendingArrayElementType, pendingArrayElementType)) {
            failWithMessage(assertjErrorMessage, actual, pendingArrayElementType, actualPendingArrayElementType);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements contains the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     *
     * @param pendingArrayElements the given elements that should be contained in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasPendingArrayElements(io.quarkiverse.qubit.deployment.ast.LambdaExpression... pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (pendingArrayElements == null)
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getPendingArrayElements(), pendingArrayElements);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements contains the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements in Collection.
     *
     * @param pendingArrayElements the given elements that should be contained in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasPendingArrayElements(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (pendingArrayElements == null) {
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getPendingArrayElements(), pendingArrayElements.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements and nothing else in whatever order.
     *
     * @param pendingArrayElements the given elements that should be contained in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasOnlyPendingArrayElements(io.quarkiverse.qubit.deployment.ast.LambdaExpression... pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (pendingArrayElements == null)
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getPendingArrayElements(), pendingArrayElements);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements in Collection and nothing else in whatever order.
     *
     * @param pendingArrayElements the given elements that should be contained in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasOnlyPendingArrayElements(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (pendingArrayElements == null) {
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getPendingArrayElements(), pendingArrayElements.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements does not contain the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     *
     * @param pendingArrayElements the given elements that should not be in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements contains any given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S doesNotHavePendingArrayElements(io.quarkiverse.qubit.deployment.ast.LambdaExpression... pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (pendingArrayElements == null)
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getPendingArrayElements(), pendingArrayElements);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's pendingArrayElements does not contain the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements in Collection.
     *
     * @param pendingArrayElements the given elements that should not be in actual AnalysisContext's pendingArrayElements.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements contains any given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S doesNotHavePendingArrayElements(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> pendingArrayElements) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (pendingArrayElements == null) {
            failWithMessage("Expecting pendingArrayElements parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getPendingArrayElements(), pendingArrayElements.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has no pendingArrayElements.
     *
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's pendingArrayElements is not empty.
     */
    public S hasNoPendingArrayElements() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // we override the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have pendingArrayElements but had :\n  <%s>";

        // check
        if (actual.getPendingArrayElements().iterator().hasNext()) {
            failWithMessage(assertjErrorMessage, actual, actual.getPendingArrayElements());
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's secondEntityParameterIndex is equal to the given one.
     *
     * @param secondEntityParameterIndex the given secondEntityParameterIndex to compare the actual AnalysisContext's
     *        secondEntityParameterIndex to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's secondEntityParameterIndex is not equal to the given one.
     */
    public S hasSecondEntityParameterIndex(int secondEntityParameterIndex) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting secondEntityParameterIndex of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualSecondEntityParameterIndex = actual.getSecondEntityParameterIndex();
        if (actualSecondEntityParameterIndex != secondEntityParameterIndex) {
            failWithMessage(assertjErrorMessage, actual, secondEntityParameterIndex, actualSecondEntityParameterIndex);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has seen branch.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext does not have seen branch.
     */
    public S hasSeenBranch() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasSeenBranch()) {
            failWithMessage("\nExpecting that actual AnalysisContext has seen branch but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext does not have seen branch.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext has seen branch.
     */
    public S doesNotHaveSeenBranch() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasSeenBranch()) {
            failWithMessage("\nExpecting that actual AnalysisContext does not have seen branch but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has skip pending.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext does not have skip pending.
     */
    public S hasSkipPending() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.hasSkipPending()) {
            failWithMessage("\nExpecting that actual AnalysisContext has skip pending but does not have.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext does not have skip pending.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext has skip pending.
     */
    public S doesNotHaveSkipPending() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.hasSkipPending()) {
            failWithMessage("\nExpecting that actual AnalysisContext does not have skip pending but has.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack contains the given io.quarkiverse.qubit.deployment.ast.LambdaExpression
     * elements.
     *
     * @param stack the given elements that should be contained in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasStack(io.quarkiverse.qubit.deployment.ast.LambdaExpression... stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (stack == null)
            failWithMessage("Expecting stack parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getStack(), stack);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack contains the given io.quarkiverse.qubit.deployment.ast.LambdaExpression
     * elements in Collection.
     *
     * @param stack the given elements that should be contained in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasStack(java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (stack == null) {
            failWithMessage("Expecting stack parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getStack(), stack.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements and nothing else in whatever order.
     *
     * @param stack the given elements that should be contained in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasOnlyStack(io.quarkiverse.qubit.deployment.ast.LambdaExpression... stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (stack == null)
            failWithMessage("Expecting stack parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getStack(), stack);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements in Collection and nothing else in whatever order.
     *
     * @param stack the given elements that should be contained in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack does not contain all given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S hasOnlyStack(java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (stack == null) {
            failWithMessage("Expecting stack parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getStack(), stack.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack does not contain the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     *
     * @param stack the given elements that should not be in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack contains any given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S doesNotHaveStack(io.quarkiverse.qubit.deployment.ast.LambdaExpression... stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression varargs is not null.
        if (stack == null)
            failWithMessage("Expecting stack parameter not to be null.");

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getStack(), stack);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stack does not contain the given
     * io.quarkiverse.qubit.deployment.ast.LambdaExpression elements in Collection.
     *
     * @param stack the given elements that should not be in actual AnalysisContext's stack.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack contains any given
     *         io.quarkiverse.qubit.deployment.ast.LambdaExpression elements.
     */
    public S doesNotHaveStack(java.util.Collection<? extends io.quarkiverse.qubit.deployment.ast.LambdaExpression> stack) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.ast.LambdaExpression collection is not null.
        if (stack == null) {
            failWithMessage("Expecting stack parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getStack(), stack.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has no stack.
     *
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's stack is not empty.
     */
    public S hasNoStack() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // we override the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have stack but had :\n  <%s>";

        // check
        if (actual.getStack().iterator().hasNext()) {
            failWithMessage(assertjErrorMessage, actual, actual.getStack());
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is stack empty.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is not stack empty.
     */
    public S isStackEmpty() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isStackEmpty()) {
            failWithMessage("\nExpecting that actual AnalysisContext is stack empty but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext is not stack empty.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext is stack empty.
     */
    public S isNotStackEmpty() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isStackEmpty()) {
            failWithMessage("\nExpecting that actual AnalysisContext is not stack empty but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's stackSize is equal to the given one.
     *
     * @param stackSize the given stackSize to compare the actual AnalysisContext's stackSize to.
     * @return this assertion object.
     * @throws AssertionError - if the actual AnalysisContext's stackSize is not equal to the given one.
     */
    public S hasStackSize(int stackSize) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting stackSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // check
        int actualStackSize = actual.getStackSize();
        if (actualStackSize != stackSize) {
            failWithMessage(assertjErrorMessage, actual, stackSize, actualStackSize);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns contains the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     *
     * @param ternaryPatterns the given elements that should be contained in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns does not contain all given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S hasTernaryPatterns(
            io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern... ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern varargs is not null.
        if (ternaryPatterns == null)
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getTernaryPatterns(), ternaryPatterns);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns contains the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements in Collection.
     *
     * @param ternaryPatterns the given elements that should be contained in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns does not contain all given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S hasTernaryPatterns(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern> ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern collection is not null.
        if (ternaryPatterns == null) {
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContains(info, actual.getTernaryPatterns(), ternaryPatterns.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements and nothing else in whatever
     * order.
     *
     * @param ternaryPatterns the given elements that should be contained in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns does not contain all given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S hasOnlyTernaryPatterns(
            io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern... ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern varargs is not null.
        if (ternaryPatterns == null)
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getTernaryPatterns(), ternaryPatterns);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns contains <b>only</b> the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements in Collection and nothing else in
     * whatever order.
     *
     * @param ternaryPatterns the given elements that should be contained in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns does not contain all given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S hasOnlyTernaryPatterns(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern> ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern collection is not null.
        if (ternaryPatterns == null) {
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
        Iterables.instance().assertContainsOnly(info, actual.getTernaryPatterns(), ternaryPatterns.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns does not contain the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     *
     * @param ternaryPatterns the given elements that should not be in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns contains any given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S doesNotHaveTernaryPatterns(
            io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern... ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern varargs is not null.
        if (ternaryPatterns == null)
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getTernaryPatterns(), ternaryPatterns);

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext's ternaryPatterns does not contain the given
     * io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements in Collection.
     *
     * @param ternaryPatterns the given elements that should not be in actual AnalysisContext's ternaryPatterns.
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns contains any given
     *         io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern elements.
     */
    public S doesNotHaveTernaryPatterns(
            java.util.Collection<? extends io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern> ternaryPatterns) {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // check that given io.quarkiverse.qubit.deployment.analysis.TernaryPatternDetector.TernaryPattern collection is not null.
        if (ternaryPatterns == null) {
            failWithMessage("Expecting ternaryPatterns parameter not to be null.");
            return myself; // to fool Eclipse "Null pointer access" warning on toArray.
        }

        // check with standard error message (use overridingErrorMessage before contains to set your own message).
        Iterables.instance().assertDoesNotContain(info, actual.getTernaryPatterns(), ternaryPatterns.toArray());

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual AnalysisContext has no ternaryPatterns.
     *
     * @return this assertion object.
     * @throws AssertionError if the actual AnalysisContext's ternaryPatterns is not empty.
     */
    public S hasNoTernaryPatterns() {
        // check that actual AnalysisContext we want to make assertions on is not null.
        isNotNull();

        // we override the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have ternaryPatterns but had :\n  <%s>";

        // check
        if (actual.getTernaryPatterns().iterator().hasNext()) {
            failWithMessage(assertjErrorMessage, actual, actual.getTernaryPatterns());
        }

        // return the current assertion for method chaining
        return myself;
    }

}
