package io.quarkiverse.qubit.deployment.analysis.instruction;

/**
 * {@link AnalysisContext} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractAnalysisContextAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class AnalysisContextAssert extends AbstractAnalysisContextAssert<AnalysisContextAssert, AnalysisContext> {

    /**
     * Creates a new <code>{@link AnalysisContextAssert}</code> to make assertions on actual AnalysisContext.
     *
     * @param actual the AnalysisContext we want to make assertions on.
     */
    public AnalysisContextAssert(AnalysisContext actual) {
        super(actual, AnalysisContextAssert.class);
    }

    /**
     * An entry point for AnalysisContextAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myAnalysisContext)</code> and get specific assertion with
     * code completion.
     *
     * @param actual the AnalysisContext we want to make assertions on.
     * @return a new <code>{@link AnalysisContextAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static AnalysisContextAssert assertThat(AnalysisContext actual) {
        return new AnalysisContextAssert(actual);
    }
}
