package io.quarkiverse.qubit.deployment.criteria;

import java.util.ArrayList;
import java.util.List;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.*;

/**
 * Inspects generated bytecode to extract method invocations.
 * Used to verify that the correct Criteria API methods are being generated.
 */
public class BytecodeInspector {

    private final byte[] bytecode;
    private final List<MethodInvocation> invocations = new ArrayList<>();

    public BytecodeInspector(byte[] bytecode) {
        this.bytecode = bytecode;
        analyzeBytecode();
    }

    /**
     * Gets all method invocations found in the bytecode.
     */
    public List<MethodInvocation> getInvocations() {
        return List.copyOf(invocations);
    }

    /**
     * Analyzes the bytecode and extracts method invocations.
     */
    private void analyzeBytecode() {
        try {
            ClassReader reader = new ClassReader(bytecode);
            ClassNode classNode = new ClassNode();
            // Skip debug info and frames - not needed for bytecode inspection
            reader.accept(classNode, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);

            // Analyze all methods in the class
            for (MethodNode method : classNode.methods) {
                analyzeMethod(method);
            }
        } catch (Exception e) {
            throw new RuntimeException("Failed to analyze bytecode", e);
        }
    }

    /**
     * Analyzes a single method and extracts invocations.
     */
    private void analyzeMethod(MethodNode method) {
        for (AbstractInsnNode insn : method.instructions) {
            if (insn instanceof MethodInsnNode methodInsn) {
                invocations.add(new MethodInvocation(
                        methodInsn.owner,
                        methodInsn.name,
                        methodInsn.desc));
            } else if (insn instanceof LdcInsnNode ldcInsn) {
                // Record constant values (useful for verifying field names, literal values)
                invocations.add(new MethodInvocation(
                        "LDC",
                        ldcInsn.cst.toString(),
                        ldcInsn.cst.getClass().getSimpleName()));
            }
        }
    }

    /**
     * Represents a method invocation found in bytecode.
     */
    public record MethodInvocation(String owner, String name, String descriptor) {

        /**
         * Checks if this invocation is a call to a CriteriaBuilder method.
         */
        public boolean isCriteriaBuilderMethod() {
            return owner.contains("CriteriaBuilder");
        }

        /**
         * Checks if this invocation is a specific method call.
         */
        public boolean isMethod(String methodName) {
            return name.equals(methodName);
        }

        /**
         * Checks if this is a constant value.
         */
        public boolean isConstant(Object value) {
            return "LDC".equals(owner) && name.equals(value.toString());
        }

        @Override
        public String toString() {
            if ("LDC".equals(owner)) {
                return "constant: " + name;
            }
            return owner.substring(owner.lastIndexOf('/') + 1) + "." + name + descriptor;
        }
    }
}
