package io.quarkiverse.qubit.deployment.criteria;

import static io.quarkiverse.qubit.runtime.internal.QubitConstants.QUERY_SPEC_DESCRIPTOR;
import static org.assertj.core.api.Assertions.assertThat;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;

import org.objectweb.asm.Handle;

import io.quarkiverse.qubit.deployment.analysis.LambdaBytecodeAnalyzer;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression;
import io.quarkiverse.qubit.deployment.generation.CriteriaExpressionGenerator;
import io.quarkiverse.qubit.deployment.testutil.AbstractLambdaAnalyzer;
import io.quarkus.gizmo2.Expr;
import io.quarkus.gizmo2.Gizmo;
import io.quarkus.gizmo2.ParamVar;
import io.quarkus.logging.Log;

/**
 * Base class for Criteria query structure verification tests.
 *
 * <p>
 * This test infrastructure verifies that lambda expressions are correctly
 * transformed into JPA Criteria API query structures by:
 * <ol>
 * <li>Analyzing lambda bytecode to extract AST</li>
 * <li>Using CriteriaExpressionGenerator to generate Criteria query building bytecode</li>
 * <li>Inspecting the generated bytecode to verify correct Criteria API calls</li>
 * </ol>
 *
 * <p>
 * <strong>No Database or Execution Required</strong>: These tests verify
 * the bytecode generation logic without executing queries or requiring a database.
 *
 * <p>
 * Extends {@link AbstractLambdaAnalyzer} to share common infrastructure
 * with bytecode analysis tests.
 */
public abstract class CriteriaQueryTestBase extends AbstractLambdaAnalyzer {

    private static final String SOURCES_CLASS_NAME = "io.quarkiverse.qubit.deployment.testutil.LambdaTestSources";

    @Override
    protected String getSourcesClassName() {
        return SOURCES_CLASS_NAME;
    }

    @Override
    protected String getDescriptorPattern() {
        return QUERY_SPEC_DESCRIPTOR;
    }

    /**
     * Analyzes a lambda method from LambdaTestSources and returns its AST.
     */
    protected LambdaExpression analyzeLambda(String methodName) {
        try {
            Handle lambdaHandle = getLambdaHandle(methodName);
            byte[] classBytes = getSourceClassBytes();

            LambdaBytecodeAnalyzer analyzer = new LambdaBytecodeAnalyzer();
            return analyzer.analyze(classBytes, lambdaHandle.getName(), lambdaHandle.getDesc());
        } catch (Exception e) {
            throw new RuntimeException("Failed to analyze lambda: " + methodName, e);
        }
    }

    /**
     * Generates Criteria query building bytecode for the given lambda expression.
     */
    protected CriteriaQueryStructure generateCriteriaQuery(LambdaExpression expression) {
        return generateCriteriaQuery(expression, "TestEntity");
    }

    /**
     * Generates Criteria query building bytecode and inspects it for verification.
     */
    protected CriteriaQueryStructure generateCriteriaQuery(LambdaExpression expression, String entityName) {
        CriteriaQueryStructure structure = new CriteriaQueryStructure(entityName);

        try {
            // Generate a unique class name
            String className = "io.quarkiverse.qubit.test.TestQueryExecutor_" + System.nanoTime();

            // Capture generated bytecode
            Map<String, byte[]> classData = new HashMap<>();

            // Generate the bytecode using Gizmo2
            // Gizmo2 passes class internal name (e.g., "io/quarkiverse/qubit/test/TestQueryExecutor_xxx") as key
            Gizmo gizmo = Gizmo.create(classData::put);
            // Track predicate generation state via holder
            final boolean[] predicateGenerated = { false };

            gizmo.class_(className, cc -> {
                cc.public_();

                // Create a method that builds the Criteria query
                cc.method("buildPredicate", mc -> {
                    mc.public_();
                    mc.returning(Predicate.class);
                    ParamVar cb = mc.parameter("cb", CriteriaBuilder.class);
                    ParamVar root = mc.parameter("root", Root.class);
                    ParamVar capturedValues = mc.parameter("capturedValues", Object[].class);

                    mc.body(bc -> {
                        // Generate the predicate building code using CriteriaExpressionGenerator directly
                        CriteriaExpressionGenerator generator = new CriteriaExpressionGenerator();
                        Expr predicate = generator.generatePredicate(bc, expression, cb, root, capturedValues);

                        predicateGenerated[0] = predicate != null;
                        bc.return_(predicate);
                    });
                });
            });

            structure.setPredicateGenerated(predicateGenerated[0]);

            // Get the generated bytecode
            // Gizmo2 uses internal name with .class suffix (e.g., "io/package/Class.class")
            String classFileName = className.replace('.', '/') + ".class";
            byte[] bytecode = classData.get(classFileName);

            if (bytecode != null) {
                // Inspect the bytecode
                BytecodeInspector inspector = new BytecodeInspector(bytecode);
                structure.setInspector(inspector);
                structure.setGenerationSuccessful(true);
            } else {
                structure.setGenerationSuccessful(false);
                structure.setErrorMessage("No bytecode generated");
            }

        } catch (Exception e) {
            Log.errorf(e, "Failed to generate Criteria query for expression: %s", expression);
            structure.setGenerationSuccessful(false);
            structure.setErrorMessage(e.getMessage());
        }

        return structure;
    }

    /**
     * Verifies that Criteria query generation succeeds.
     */
    protected void assertCriteriaGenerationSucceeds(LambdaExpression expression) {
        CriteriaQueryStructure structure = generateCriteriaQuery(expression);
        assertThat(structure.isGenerationSuccessful())
                .as("Criteria query generation should succeed for: " + expression +
                        (structure.getErrorMessage() != null ? " - Error: " + structure.getErrorMessage() : ""))
                .isTrue();
        assertThat(structure.isPredicateGenerated())
                .as("Predicate should be generated for: " + expression)
                .isTrue();
    }

    /**
     * Full test pattern: analyze lambda + verify Criteria generation succeeds.
     */
    protected void testCriteriaGeneration(String lambdaMethodName) {
        LambdaExpression expr = analyzeLambda(lambdaMethodName);
        assertCriteriaGenerationSucceeds(expr);
    }

    // ==================== CRITERIA-SPECIFIC ASSERTION HELPERS ====================

    /**
     * Asserts that a specific Criteria API method was called.
     */
    protected void assertCriteriaMethodCalled(CriteriaQueryStructure structure, String methodName) {
        boolean called = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isMethod(methodName));
        assertThat(called)
                .as("Method " + methodName + " should have been called")
                .isTrue();
    }

    /**
     * Asserts that a specific method was called a certain number of times.
     */
    protected void assertCriteriaMethodCallCount(CriteriaQueryStructure structure, String methodName, int expectedCount) {
        long count = structure.getInvocations().stream()
                .filter(inv -> inv.isMethod(methodName))
                .count();
        assertThat(count)
                .as("Method " + methodName + " call count")
                .isEqualTo(expectedCount);
    }

    /**
     * Asserts that a field name appears as a constant (for root.get("fieldName")).
     */
    protected void assertFieldAccessed(CriteriaQueryStructure structure, String fieldName) {
        boolean accessed = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isConstant(fieldName));
        assertThat(accessed)
                .as("Field '" + fieldName + "' should appear as a constant (for root.get)")
                .isTrue();
    }

    /**
     * Asserts that a constant value was used.
     */
    protected void assertConstantUsed(CriteriaQueryStructure structure, Object constantValue) {
        boolean found = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isConstant(constantValue));
        assertThat(found)
                .as("Constant value '" + constantValue + "' should have been used")
                .isTrue();
    }

    /**
     * Asserts that specific Criteria API methods were called.
     */
    protected void assertCriteriaStructure(CriteriaQueryStructure structure, String... expectedMethods) {
        for (String expectedMethod : expectedMethods) {
            assertCriteriaMethodCalled(structure, expectedMethod);
        }
    }

    /**
     * Represents the structure of a generated Criteria query for verification.
     */
    protected static class CriteriaQueryStructure {
        private final String entityName;
        private BytecodeInspector inspector;
        private boolean generationSuccessful;
        private boolean predicateGenerated;
        private String errorMessage;

        public CriteriaQueryStructure(String entityName) {
            this.entityName = entityName;
        }

        public String getEntityName() {
            return entityName;
        }

        public void setInspector(BytecodeInspector inspector) {
            this.inspector = inspector;
        }

        public boolean isGenerationSuccessful() {
            return generationSuccessful;
        }

        public void setGenerationSuccessful(boolean successful) {
            this.generationSuccessful = successful;
        }

        public boolean isPredicateGenerated() {
            return predicateGenerated;
        }

        public void setPredicateGenerated(boolean generated) {
            this.predicateGenerated = generated;
        }

        public String getErrorMessage() {
            return errorMessage;
        }

        public void setErrorMessage(String message) {
            this.errorMessage = message;
        }

        /**
         * Gets all method invocations found in the generated bytecode.
         */
        public List<BytecodeInspector.MethodInvocation> getInvocations() {
            return inspector != null ? inspector.getInvocations() : List.of();
        }

        @Override
        public String toString() {
            return "CriteriaQueryStructure{" +
                    "entityName='" + entityName + '\'' +
                    ", generationSuccessful=" + generationSuccessful +
                    ", predicateGenerated=" + predicateGenerated +
                    ", invocations=" + (inspector != null ? inspector.getInvocations().size() : 0) +
                    ", errorMessage='" + errorMessage + '\'' +
                    '}';
        }
    }
}
