package io.quarkiverse.qubit.deployment.generation;

import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_COUNT;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_CREATE_QUERY;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_FROM;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_SELECT;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.EM_CREATE_QUERY;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.EM_GET_CRITERIA_BUILDER;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.FROM_JOIN;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.PATH_GET;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.TQ_GET_RESULT_LIST;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.TQ_GET_SINGLE_RESULT;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.QE_EXECUTE;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

import jakarta.persistence.EntityManager;

import org.jspecify.annotations.Nullable;

import io.quarkiverse.qubit.deployment.analysis.CallSite;
import io.quarkiverse.qubit.deployment.analysis.LambdaAnalysisResult.SortExpression;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression;
import io.quarkiverse.qubit.deployment.generation.join.JoinQueryBuilder;
import io.quarkiverse.qubit.deployment.generation.join.JoinQueryContext;
import io.quarkiverse.qubit.deployment.generation.join.JoinSelectionStrategy;
import io.quarkiverse.qubit.deployment.generation.join.StandardClauseApplier;
import io.quarkiverse.qubit.deployment.metrics.BuildMetricsCollector;
import io.quarkiverse.qubit.runtime.internal.QueryExecutor;
import io.quarkus.gizmo2.Const;
import io.quarkus.gizmo2.Expr;
import io.quarkus.gizmo2.Gizmo;
import io.quarkus.gizmo2.LocalVar;
import io.quarkus.gizmo2.creator.BlockCreator;
import io.quarkus.logging.Log;

/**
 * Generates query executor classes that execute JPA Criteria API queries from lambda expressions.
 */
public class QueryExecutorClassGenerator {

    /**
     * Static cache for generated bytecode.
     * <p>
     * Key: fully qualified class name (derived from lambda hash)
     * Value: generated bytecode
     * <p>
     * This cache provides significant performance improvement in:
     * <ul>
     * <li>Dev mode hot reload - same queries don't need regeneration</li>
     * <li>Multi-module builds - shared queries across modules</li>
     * </ul>
     * <p>
     * The cache is keyed by class name which includes the lambda hash,
     * so semantically identical queries will share the same cached bytecode.
     */
    private static final ConcurrentHashMap<String, byte[]> BYTECODE_CACHE = new ConcurrentHashMap<>();

    /** Clears the bytecode cache. Called at the start of each build for fresh state. */
    public static void clearCache() {
        BYTECODE_CACHE.clear();
        Log.debug("QueryExecutorClassGenerator bytecode cache cleared");
    }

    /** Returns the current cache size (for metrics/debugging). */
    public static int getCacheSize() {
        return BYTECODE_CACHE.size();
    }

    private final CriteriaExpressionGenerator expressionGenerator = new CriteriaExpressionGenerator();

    /** Join query builder using Template Method pattern. */
    private final JoinQueryBuilder joinQueryBuilder;

    private final StandardClauseApplier clauseApplier = new StandardClauseApplier(expressionGenerator);

    /** Optional metrics collector for timing Gizmo2 code generation. */
    private @Nullable BuildMetricsCollector metricsCollector;

    public QueryExecutorClassGenerator() {
        this.joinQueryBuilder = new JoinQueryBuilder(expressionGenerator, clauseApplier);
    }

    /** Sets the metrics collector for timing code generation. */
    public void setMetricsCollector(@Nullable BuildMetricsCollector metricsCollector) {
        this.metricsCollector = metricsCollector;
    }

    /** Context for query generation methods with shared parameters. */
    private record QueryGenContext(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            List<?> sortExpressions,
            Expr capturedValues,
            Expr offset,
            Expr limit,
            Expr distinct) {
    }

    /** JPA Criteria API query setup: CriteriaBuilder, CriteriaQuery, and Root stored as LocalVar for Gizmo2. */
    record QuerySetup(
            LocalVar cb,
            LocalVar query,
            LocalVar root) {
    }

    /** Sets up CriteriaBuilder, CriteriaQuery, and Root in a single call. Uses LocalVar for Gizmo2 stack management. */
    QuerySetup setupQuery(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            Expr resultClass) {
        // Use LocalVar to store values that are used across multiple operations (Gizmo2 requirement)
        LocalVar cb = bc.localVar("cb", bc.invokeInterface(EM_GET_CRITERIA_BUILDER, em));
        LocalVar query = bc.localVar("query", bc.invokeInterface(CB_CREATE_QUERY, cb, resultClass));
        LocalVar root = bc.localVar("root", bc.invokeInterface(CQ_FROM, query, entityClass));
        return new QuerySetup(cb, query, root);
    }

    /** Sets up query with Object.class result type (projections, groups). */
    QuerySetup setupQueryForObject(BlockCreator bc, Expr em, Expr entityClass) {
        return setupQuery(bc, em, entityClass, Const.of(Object.class));
    }

    /** Sets up query with Long.class result type (count queries). */
    QuerySetup setupQueryForLong(BlockCreator bc, Expr em, Expr entityClass) {
        return setupQuery(bc, em, entityClass, Const.of(Long.class));
    }

    /** Generates query executor class with WHERE, SELECT, ORDER BY, and aggregation. */
    public byte[] generateQueryExecutorClass(
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression,
            List<?> sortExpressions,
            LambdaExpression aggregationExpression,
            String aggregationType,
            String className,
            boolean isCountQuery,
            boolean isAggregationQuery) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Execute method signature includes offset, limit, and distinct parameters
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        Expr result;
                        if (isAggregationQuery) {
                            // Delegate aggregation queries (min, max, avg, sum*) to AggregationQueryGenerator
                            var aggGen = new AggregationQueryGenerator(expressionGenerator, clauseApplier,
                                    QueryExecutorClassGenerator.this);
                            result = aggGen.generateAggregationQueryBody(bc, em, entityClassParam, predicateExpression,
                                    aggregationExpression, aggregationType, capturedValues);
                        } else if (isCountQuery) {
                            // Count queries ignore pagination and distinct parameters
                            result = generateCountQueryBody(bc, em, entityClassParam, predicateExpression, capturedValues);
                        } else {
                            QueryGenContext ctx = new QueryGenContext(bc, em, entityClassParam,
                                    sortExpressions, capturedValues, offset, limit, distinct);
                            result = generateListQueryBody(ctx, predicateExpression, projectionExpression);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates query executor for JOIN queries with bi-entity predicates and projections. */
    public byte[] generateJoinQueryExecutorClass(
            LambdaExpression joinRelationshipExpression,
            LambdaExpression sourcePredicateExpression,
            LambdaExpression biEntityPredicateExpression,
            LambdaExpression biEntityProjectionExpression,
            List<SortExpression> sortExpressions,
            CallSite.JoinType joinType,
            String className,
            boolean isCountQuery,
            boolean isSelectJoined,
            boolean isJoinProjection) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Same execute method signature as regular queries
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        Expr result;
                        if (isCountQuery) {
                            result = generateJoinCountQueryBody(
                                    bc, em, entityClassParam,
                                    joinRelationshipExpression, sourcePredicateExpression,
                                    biEntityPredicateExpression,
                                    joinType, capturedValues);
                        } else {
                            // Use Template Method pattern with Strategy for the three join query variants
                            JoinQueryContext ctx = new JoinQueryContext(
                                    bc, em, entityClassParam,
                                    joinRelationshipExpression, sourcePredicateExpression,
                                    biEntityPredicateExpression,
                                    joinType, sortExpressions, capturedValues, offset, limit, distinct);

                            // Determine selection strategy based on query type
                            JoinSelectionStrategy strategy;
                            if (isJoinProjection) {
                                // select() with BiQuerySpec returns projected results
                                Expr objectClass = Const.of(Object.class);
                                strategy = new JoinSelectionStrategy.SelectProjection(objectClass,
                                        biEntityProjectionExpression);
                            } else if (isSelectJoined) {
                                // selectJoined() returns joined entities instead of source entities
                                Expr objectClass = Const.of(Object.class);
                                strategy = new JoinSelectionStrategy.SelectJoined(objectClass);
                            } else {
                                // Default: return root entities
                                strategy = new JoinSelectionStrategy.SelectRoot(entityClassParam);
                            }

                            result = joinQueryBuilder.build(ctx, strategy);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates query executor for GROUP BY with optional HAVING, aggregations, and sorting. */
    public byte[] generateGroupQueryExecutorClass(
            LambdaExpression predicateExpression,
            LambdaExpression groupByKeyExpression,
            LambdaExpression havingExpression,
            LambdaExpression groupSelectExpression,
            List<SortExpression> groupSortExpressions,
            String className,
            boolean isCountQuery) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Same execute method signature as regular queries
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        // Delegate to GroupQueryGenerator
                        var groupGen = new GroupQueryGenerator(expressionGenerator, clauseApplier,
                                QueryExecutorClassGenerator.this);

                        // Create base context with common parameters
                        var baseCtx = new GroupQueryGenerator.GroupQueryContext(
                                bc, em, entityClassParam,
                                predicateExpression, groupByKeyExpression,
                                havingExpression, capturedValues);

                        Expr result;
                        if (isCountQuery) {
                            result = groupGen.generateGroupCountQueryBody(baseCtx);
                        } else {
                            var listCtx = new GroupQueryGenerator.GroupListContext(
                                    baseCtx, groupSelectExpression, groupSortExpressions,
                                    offset, limit, distinct);
                            result = groupGen.generateGroupQueryBody(listCtx);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates LIST query with WHERE, SELECT, ORDER BY, and pagination. */
    private Expr generateListQueryBody(
            QueryGenContext ctx,
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression) {

        // Combined WHERE + SELECT query
        if (predicateExpression != null && projectionExpression != null) {
            return generateCombinedWhereSelectQuery(ctx, predicateExpression, projectionExpression);
        }

        // Projection query (select().toList())
        if (projectionExpression != null) {
            return generateProjectionQuery(ctx, projectionExpression);
        }

        // Both predicate and no-predicate paths share the same query execution flow
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), ctx.entityClass());

        // Apply WHERE predicate if present (with subquery support)
        if (predicateExpression != null) {
            Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                    ctx.bc(), predicateExpression, setup.cb(), setup.query(), setup.root(), ctx.capturedValues());
            clauseApplier.applyWherePredicate(ctx.bc(), setup.query(), predicate);
        }

        // Execute common list query flow: ORDER BY, DISTINCT, pagination, getResultList()
        return executeListQuery(ctx, setup);
    }

    /** Executes list query: ORDER BY, DISTINCT, pagination, getResultList(). */
    private Expr executeListQuery(QueryGenContext ctx, QuerySetup setup) {
        applyOrderBy(ctx.bc(), setup.query(), setup.root(), setup.cb(),
                ctx.sortExpressions(), ctx.capturedValues(), null);
        clauseApplier.applyDistinct(ctx.bc(), setup.query(), ctx.distinct());
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery",
                ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), setup.query()));
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates COUNT query with subquery support. */
    private Expr generateCountQueryBody(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression expression,
            Expr capturedValues) {

        QuerySetup setup = setupQueryForLong(bc, em, entityClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();
        Expr countExpr = bc.invokeInterface(CB_COUNT, cb, root);
        bc.invokeInterface(CQ_SELECT, query, countExpr);
        Expr predicate = expressionGenerator.generatePredicateWithSubqueries(bc, expression, cb, query, root, capturedValues);
        clauseApplier.applyWherePredicate(bc, query, predicate);
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, em, query);
        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /** Generates JOIN COUNT query with relationship navigation and bi-entity predicates. */
    private Expr generateJoinCountQueryBody(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression joinRelationshipExpression,
            LambdaExpression sourcePredicateExpression,
            LambdaExpression biEntityPredicateExpression,
            CallSite.JoinType joinType,
            Expr capturedValues) {

        // Setup query for Long (count result)
        QuerySetup setup = setupQueryForLong(bc, em, entityClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Extract relationship field name from join relationship expression
        String relationshipFieldName = joinRelationshipExpression.getFieldNameOrThrow();

        // Create Join by calling root.join(relationshipFieldName, JoinType)
        Expr relationshipName = Const.of(relationshipFieldName);
        Expr jpaJoinType = GizmoHelper.loadJpaJoinType(joinType);
        Expr joinHandle = bc.invokeInterface(FROM_JOIN, root, relationshipName, jpaJoinType);

        // SELECT COUNT(root)
        Expr countExpr = bc.invokeInterface(CB_COUNT, cb, root);
        bc.invokeInterface(CQ_SELECT, query, countExpr);

        // Apply WHERE predicates — combine with cb.and() if both exist
        // (CriteriaQuery.where() replaces, so multiple calls would lose earlier predicates)
        Expr sourcePredicate = sourcePredicateExpression != null
                ? expressionGenerator.generatePredicateWithSubqueries(
                        bc, sourcePredicateExpression, cb, query, root, capturedValues)
                : null;
        Expr biEntityPredicate = biEntityPredicateExpression != null
                ? expressionGenerator.generateBiEntityPredicateWithSubqueries(
                        bc, biEntityPredicateExpression, cb, query, root, joinHandle, capturedValues)
                : null;
        Expr combinedPredicate = GizmoHelper.combinePredicatesWithAnd(bc, cb, sourcePredicate, biEntityPredicate);
        if (combinedPredicate != null) {
            clauseApplier.applyWherePredicate(bc, query, combinedPredicate);
        }

        // Create TypedQuery
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, em, query);

        // Return getSingleResult() for count
        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /** Generates simple field projection: select(p -> p.field).toList(). */
    private Expr generateSimpleFieldProjectionQuery(
            QueryGenContext ctx,
            LambdaExpression.FieldAccess fieldAccess) {

        // Load field type class and setup query
        Expr fieldTypeClass = Const.of(fieldAccess.fieldType());
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), fieldTypeClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate root.get("fieldName")
        // Use LocalVar for path since it's used in multiple operations (Gizmo2 requirement)
        Expr fieldName = Const.of(fieldAccess.fieldName());
        LocalVar path = ctx.bc().localVar("path", ctx.bc().invokeInterface(PATH_GET, root, fieldName));

        // query.select(path)
        ctx.bc().invokeInterface(CQ_SELECT, query, path);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), path);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates projection query for field access or expressions. */
    private Expr generateProjectionQuery(
            QueryGenContext ctx,
            LambdaExpression projectionExpression) {

        // Simple field access projection - use type-safe query
        if (projectionExpression instanceof LambdaExpression.FieldAccess fieldAccess) {
            return generateSimpleFieldProjectionQuery(ctx, fieldAccess);
        }

        // Expression projection - use Object query
        QuerySetup setup = setupQueryForObject(ctx.bc(), ctx.em(), ctx.entityClass());
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate the projection expression as JPA Expression
        // Use LocalVar since projectionExpr is used in multiple operations (Gizmo2 requirement)
        LocalVar projectionExpr = ctx.bc().localVar("projectionExpr", expressionGenerator.generateExpressionAsJpaExpression(
                ctx.bc(), projectionExpression, cb, root, ctx.capturedValues()));

        // query.select(projectionExpr)
        ctx.bc().invokeInterface(CQ_SELECT, query, projectionExpr);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), projectionExpr);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates combined WHERE + SELECT query. */
    private Expr generateCombinedWhereSelectQuery(
            QueryGenContext ctx,
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression) {

        // Determine result type based on projection expression
        Expr resultTypeClass;
        if (projectionExpression instanceof LambdaExpression.FieldAccess(_, var fieldType)) {
            // Field access projection - use field type for type safety
            resultTypeClass = Const.of(fieldType);
        } else {
            // Expression projection - use Object.class
            resultTypeClass = Const.of(Object.class);
        }

        // Setup query with the determined result type
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), resultTypeClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate WHERE predicate (with subquery support)
        Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                ctx.bc(), predicateExpression, cb, query, root, ctx.capturedValues());
        clauseApplier.applyWherePredicate(ctx.bc(), query, predicate);

        // Generate SELECT projection expression
        // Use LocalVar since projectionExpr is used in multiple operations (Gizmo2 requirement)
        LocalVar projectionExpr;
        if (projectionExpression instanceof LambdaExpression.FieldAccess(var projFieldName, _)) {
            // Simple field access - root.get("fieldName")
            Expr fieldNameHandle = Const.of(projFieldName);
            projectionExpr = ctx.bc().localVar("projectionExpr", ctx.bc().invokeInterface(PATH_GET, root, fieldNameHandle));
        } else {
            // Expression projection - use expression generator
            projectionExpr = ctx.bc().localVar("projectionExpr", expressionGenerator.generateExpressionAsJpaExpression(
                    ctx.bc(), projectionExpression, cb, root, ctx.capturedValues()));
        }

        // query.select(projectionExpr)
        ctx.bc().invokeInterface(CQ_SELECT, query, projectionExpr);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), projectionExpr);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Applies ORDER BY, using projectionExpression as fallback for identity sorts. */
    private void applyOrderBy(
            BlockCreator bc,
            Expr query,
            Expr root,
            Expr cb,
            List<?> sortExpressions,
            Expr capturedValues,
            Expr projectionExpression) {

        GizmoHelper.buildOrderByClause(bc, query, cb, sortExpressions, sortExpr -> {
            // Generate JPA Expression for the sort key extractor
            Expr sortKeyExpr = expressionGenerator.generateExpressionAsJpaExpression(
                    bc, sortExpr.keyExtractor(), cb, root, capturedValues);

            // If sort key is null (identity function like s -> s after projection),
            // use the projection expression instead
            if (sortKeyExpr == null && projectionExpression != null) {
                return projectionExpression;
            }
            return sortKeyExpr;
        });
    }
}
