package io.quarkiverse.qubit.deployment.generation;

import static io.quarkiverse.qubit.deployment.common.ExceptionMessages.unknownAggregationType;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_AVG;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_COUNT;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_COUNT_DISTINCT;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_CREATE_QUERY;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_MAX;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_MIN;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_SUM_AS_DOUBLE;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CB_SUM_AS_LONG;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_FROM;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_GROUP_BY;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_HAVING;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.CQ_SELECT;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.EM_CREATE_QUERY;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.EM_GET_CRITERIA_BUILDER;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.FROM_JOIN;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.INTEGER_LONG_VALUE;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.INTEGER_VALUE_OF;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.LIST_SIZE;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.LONG_VALUE_OF;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.PATH_GET;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.TQ_GET_RESULT_LIST;
import static io.quarkiverse.qubit.deployment.generation.MethodDescriptors.TQ_GET_SINGLE_RESULT;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_AVG;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_MAX;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_MIN;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_SUM_DOUBLE;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_SUM_INTEGER;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.AGG_TYPE_SUM_LONG;
import static io.quarkiverse.qubit.runtime.internal.QubitConstants.QE_EXECUTE;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

import jakarta.persistence.EntityManager;
import jakarta.persistence.criteria.Expression;
import jakarta.persistence.criteria.Predicate;

import org.jspecify.annotations.Nullable;

import io.quarkiverse.qubit.deployment.analysis.CallSite;
import io.quarkiverse.qubit.deployment.analysis.LambdaAnalysisResult.SortExpression;
import io.quarkiverse.qubit.deployment.ast.LambdaExpression;
import io.quarkiverse.qubit.deployment.generation.join.JoinQueryBuilder;
import io.quarkiverse.qubit.deployment.generation.join.JoinQueryContext;
import io.quarkiverse.qubit.deployment.generation.join.JoinSelectionStrategy;
import io.quarkiverse.qubit.deployment.generation.join.StandardClauseApplier;
import io.quarkiverse.qubit.deployment.metrics.BuildMetricsCollector;
import io.quarkiverse.qubit.runtime.internal.QueryExecutor;
import io.quarkus.gizmo2.Const;
import io.quarkus.gizmo2.Expr;
import io.quarkus.gizmo2.Gizmo;
import io.quarkus.gizmo2.LocalVar;
import io.quarkus.gizmo2.creator.BlockCreator;
import io.quarkus.logging.Log;

/**
 * Generates query executor classes that execute JPA Criteria API queries from lambda expressions.
 */
public class QueryExecutorClassGenerator {

    /**
     * Static cache for generated bytecode.
     * <p>
     * Key: fully qualified class name (derived from lambda hash)
     * Value: generated bytecode
     * <p>
     * This cache provides significant performance improvement in:
     * <ul>
     * <li>Dev mode hot reload - same queries don't need regeneration</li>
     * <li>Multi-module builds - shared queries across modules</li>
     * </ul>
     * <p>
     * The cache is keyed by class name which includes the lambda hash,
     * so semantically identical queries will share the same cached bytecode.
     */
    private static final ConcurrentHashMap<String, byte[]> BYTECODE_CACHE = new ConcurrentHashMap<>();

    /** Clears the bytecode cache. Called at the start of each build for fresh state. */
    public static void clearCache() {
        BYTECODE_CACHE.clear();
        Log.debug("QueryExecutorClassGenerator bytecode cache cleared");
    }

    /** Returns the current cache size (for metrics/debugging). */
    public static int getCacheSize() {
        return BYTECODE_CACHE.size();
    }

    private final CriteriaExpressionGenerator expressionGenerator = new CriteriaExpressionGenerator();

    /** Join query builder using Template Method pattern. */
    private final JoinQueryBuilder joinQueryBuilder;

    private final StandardClauseApplier clauseApplier = new StandardClauseApplier(expressionGenerator);

    /** Optional metrics collector for timing Gizmo2 code generation. */
    private @Nullable BuildMetricsCollector metricsCollector;

    public QueryExecutorClassGenerator() {
        this.joinQueryBuilder = new JoinQueryBuilder(expressionGenerator, clauseApplier);
    }

    /** Sets the metrics collector for timing code generation. */
    public void setMetricsCollector(@Nullable BuildMetricsCollector metricsCollector) {
        this.metricsCollector = metricsCollector;
    }

    /** Context for query generation methods with shared parameters. */
    private record QueryGenContext(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            List<?> sortExpressions,
            Expr capturedValues,
            Expr offset,
            Expr limit,
            Expr distinct) {
    }

    /** JPA Criteria API query setup: CriteriaBuilder, CriteriaQuery, and Root stored as LocalVar for Gizmo2. */
    private record QuerySetup(
            LocalVar cb,
            LocalVar query,
            LocalVar root) {
    }

    /** Context for GROUP BY query generation with WHERE, GROUP BY, and HAVING. */
    private record GroupQueryContext(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression predicateExpression,
            LambdaExpression groupByKeyExpression,
            LambdaExpression havingExpression,
            Expr capturedValues) {
    }

    /** Extended GROUP BY context adding select, sort, pagination, and distinct. */
    private record GroupListContext(
            GroupQueryContext base,
            LambdaExpression groupSelectExpression,
            List<SortExpression> groupSortExpressions,
            Expr offset,
            Expr limit,
            Expr distinct) {
        // Delegate accessors for convenience
        BlockCreator bc() {
            return base.bc();
        }

        Expr em() {
            return base.em();
        }

        Expr entityClass() {
            return base.entityClass();
        }

        LambdaExpression havingExpression() {
            return base.havingExpression();
        }

        Expr capturedValues() {
            return base.capturedValues();
        }
    }

    /** Sets up CriteriaBuilder, CriteriaQuery, and Root in a single call. Uses LocalVar for Gizmo2 stack management. */
    private QuerySetup setupQuery(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            Expr resultClass) {
        // Use LocalVar to store values that are used across multiple operations (Gizmo2 requirement)
        LocalVar cb = bc.localVar("cb", bc.invokeInterface(EM_GET_CRITERIA_BUILDER, em));
        LocalVar query = bc.localVar("query", bc.invokeInterface(CB_CREATE_QUERY, cb, resultClass));
        LocalVar root = bc.localVar("root", bc.invokeInterface(CQ_FROM, query, entityClass));
        return new QuerySetup(cb, query, root);
    }

    /** Sets up query with Object.class result type (projections, groups). */
    private QuerySetup setupQueryForObject(BlockCreator bc, Expr em, Expr entityClass) {
        return setupQuery(bc, em, entityClass, Const.of(Object.class));
    }

    /** Sets up query with Long.class result type (count queries). */
    private QuerySetup setupQueryForLong(BlockCreator bc, Expr em, Expr entityClass) {
        return setupQuery(bc, em, entityClass, Const.of(Long.class));
    }

    /** Generates query executor class with WHERE, SELECT, ORDER BY, and aggregation. */
    public byte[] generateQueryExecutorClass(
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression,
            List<?> sortExpressions,
            LambdaExpression aggregationExpression,
            String aggregationType,
            String className,
            boolean isCountQuery,
            boolean isAggregationQuery) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Execute method signature includes offset, limit, and distinct parameters
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        Expr result;
                        if (isAggregationQuery) {
                            // Aggregation queries (min, max, avg, sum*)
                            result = generateAggregationQueryBody(bc, em, entityClassParam, predicateExpression,
                                    aggregationExpression, aggregationType, capturedValues);
                        } else if (isCountQuery) {
                            // Count queries ignore pagination and distinct parameters
                            result = generateCountQueryBody(bc, em, entityClassParam, predicateExpression, capturedValues);
                        } else {
                            QueryGenContext ctx = new QueryGenContext(bc, em, entityClassParam,
                                    sortExpressions, capturedValues, offset, limit, distinct);
                            result = generateListQueryBody(ctx, predicateExpression, projectionExpression);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates query executor for JOIN queries with bi-entity predicates and projections. */
    public byte[] generateJoinQueryExecutorClass(
            LambdaExpression joinRelationshipExpression,
            LambdaExpression biEntityPredicateExpression,
            LambdaExpression biEntityProjectionExpression,
            List<SortExpression> sortExpressions,
            CallSite.JoinType joinType,
            String className,
            boolean isCountQuery,
            boolean isSelectJoined,
            boolean isJoinProjection) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Same execute method signature as regular queries
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        Expr result;
                        if (isCountQuery) {
                            result = generateJoinCountQueryBody(
                                    bc, em, entityClassParam,
                                    joinRelationshipExpression, biEntityPredicateExpression,
                                    joinType, capturedValues);
                        } else {
                            // Use Template Method pattern with Strategy for the three join query variants
                            JoinQueryContext ctx = new JoinQueryContext(
                                    bc, em, entityClassParam,
                                    joinRelationshipExpression, biEntityPredicateExpression,
                                    joinType, sortExpressions, capturedValues, offset, limit, distinct);

                            // Determine selection strategy based on query type
                            JoinSelectionStrategy strategy;
                            if (isJoinProjection) {
                                // select() with BiQuerySpec returns projected results
                                Expr objectClass = Const.of(Object.class);
                                strategy = new JoinSelectionStrategy.SelectProjection(objectClass,
                                        biEntityProjectionExpression);
                            } else if (isSelectJoined) {
                                // selectJoined() returns joined entities instead of source entities
                                Expr objectClass = Const.of(Object.class);
                                strategy = new JoinSelectionStrategy.SelectJoined(objectClass);
                            } else {
                                // Default: return root entities
                                strategy = new JoinSelectionStrategy.SelectRoot(entityClassParam);
                            }

                            result = joinQueryBuilder.build(ctx, strategy);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates query executor for GROUP BY with optional HAVING, aggregations, and sorting. */
    public byte[] generateGroupQueryExecutorClass(
            LambdaExpression predicateExpression,
            LambdaExpression groupByKeyExpression,
            LambdaExpression havingExpression,
            LambdaExpression groupSelectExpression,
            List<SortExpression> groupSortExpressions,
            String className,
            boolean isCountQuery) {

        // Check cache first - className is derived from lambda hash, so identical queries share bytecode
        byte[] cached = BYTECODE_CACHE.get(className);
        if (cached != null) {
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheHits();
            }
            return cached;
        }

        long startTime = System.nanoTime();
        try {
            // Holder for the generated bytecode
            final byte[][] bytecodeHolder = new byte[1][];

            // Gizmo2 ClassOutput uses ClassDesc, byte[] signature
            Gizmo gizmo = Gizmo.create((desc, bytes) -> bytecodeHolder[0] = bytes);
            gizmo.class_(className, cc -> {
                cc.implements_(QueryExecutor.class);
                cc.defaultConstructor();

                // Same execute method signature as regular queries
                cc.method(QE_EXECUTE, mc -> {
                    mc.public_();
                    mc.returning(Object.class);
                    var em = mc.parameter("em", EntityManager.class);
                    var entityClassParam = mc.parameter("entityClass", Class.class);
                    var capturedValues = mc.parameter("capturedValues", Object[].class);
                    var offset = mc.parameter("offset", Integer.class);
                    var limit = mc.parameter("limit", Integer.class);
                    var distinct = mc.parameter("distinct", Boolean.class);

                    mc.body(bc -> {
                        // Create base context with common parameters
                        GroupQueryContext baseCtx = new GroupQueryContext(
                                bc, em, entityClassParam,
                                predicateExpression, groupByKeyExpression,
                                havingExpression, capturedValues);

                        Expr result;
                        if (isCountQuery) {
                            result = generateGroupCountQueryBody(baseCtx);
                        } else {
                            GroupListContext listCtx = new GroupListContext(
                                    baseCtx, groupSelectExpression, groupSortExpressions,
                                    offset, limit, distinct);
                            result = generateGroupQueryBody(listCtx);
                        }

                        bc.return_(result);
                    });
                });
            });

            // Cache the generated bytecode for future reuse
            byte[] bytecode = bytecodeHolder[0];
            BYTECODE_CACHE.putIfAbsent(className, bytecode);
            if (metricsCollector != null) {
                metricsCollector.incrementCodeGenCacheMisses();
            }
            return bytecode;
        } finally {
            if (metricsCollector != null) {
                metricsCollector.addCodeGenerationTime(System.nanoTime() - startTime);
            }
        }
    }

    /** Generates GROUP BY query with optional WHERE, HAVING, SELECT, and ORDER BY. */
    private Expr generateGroupQueryBody(GroupListContext ctx) {
        BlockCreator bc = ctx.bc();

        // Setup query and apply common GROUP BY logic
        QuerySetup setup = setupQueryForObject(bc, ctx.em(), ctx.entityClass());
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Apply common WHERE and GROUP BY setup
        // Returns LocalVar for Gizmo2 scoping (used across HAVING, SELECT, ORDER BY)
        LocalVar groupKeyExpr = applyGroupQuerySetup(ctx.base(), setup);

        // Apply HAVING predicate if present
        if (ctx.havingExpression() != null) {
            Expr havingPredicate = expressionGenerator.generateGroupPredicate(
                    bc, ctx.havingExpression(), cb, root, groupKeyExpr, ctx.capturedValues());
            applyHavingPredicate(bc, query, havingPredicate);
        }

        // Apply SELECT projection if present
        if (ctx.groupSelectExpression() != null) {
            Expr selection = expressionGenerator.generateGroupSelectExpression(
                    bc, ctx.groupSelectExpression(), cb, root, groupKeyExpr, ctx.capturedValues());
            bc.invokeInterface(CQ_SELECT, query, selection);
        } else {
            // Default: SELECT the grouping key
            bc.invokeInterface(CQ_SELECT, query, groupKeyExpr);
        }

        // Apply ORDER BY for group queries
        applyGroupOrderBy(bc, query, root, groupKeyExpr, cb, ctx.groupSortExpressions(), ctx.capturedValues());

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(bc, query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = bc.localVar("typedQuery", bc.invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(bc, typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return bc.invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Applies WHERE predicate and generates GROUP BY key expression. */
    private Expr applyWhereAndGenerateGroupKey(GroupQueryContext ctx, QuerySetup setup) {
        BlockCreator bc = ctx.bc();

        // Apply pre-grouping WHERE predicate if present (with subquery support)
        if (ctx.predicateExpression() != null) {
            Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                    bc, ctx.predicateExpression(), setup.cb(), setup.query(), setup.root(), ctx.capturedValues());
            clauseApplier.applyWherePredicate(bc, setup.query(), predicate);
        }

        // Generate and return GROUP BY key expression
        return expressionGenerator.generateExpression(
                bc, ctx.groupByKeyExpression(), setup.cb(), setup.root(), ctx.capturedValues());
    }

    /** Applies WHERE, GROUP BY key, and GROUP BY clause setup. Returns LocalVar for Gizmo2 scoping. */
    private LocalVar applyGroupQuerySetup(GroupQueryContext ctx, QuerySetup setup) {
        // Apply WHERE and generate group key
        Expr groupKeyExpr = applyWhereAndGenerateGroupKey(ctx, setup);

        // Store in LocalVar for Gizmo2 scoping - this value is used across multiple operations
        // (HAVING predicate, SELECT expression, ORDER BY, and the GROUP BY array itself)
        LocalVar groupKeyVar = ctx.bc().localVar("groupKey", groupKeyExpr);

        // Apply GROUP BY
        LocalVar groupByArray = ctx.bc().localVar("groupByArray", ctx.bc().newEmptyArray(Expression.class, 1));
        ctx.bc().set(groupByArray.elem(0), groupKeyVar);
        ctx.bc().invokeInterface(CQ_GROUP_BY, setup.query(), groupByArray);

        return groupKeyVar;
    }

    /** Generates GROUP BY COUNT using COUNT(DISTINCT) or runtime result counting for HAVING. */
    private Expr generateGroupCountQueryBody(GroupQueryContext ctx) {
        if (ctx.havingExpression() != null) {
            return generateGroupCountWithHaving(ctx);
        } else {
            return generateGroupCountWithoutHaving(ctx);
        }
    }

    /** Generates GROUP COUNT with HAVING (counts results at runtime). */
    private Expr generateGroupCountWithHaving(GroupQueryContext ctx) {
        BlockCreator bc = ctx.bc();

        // With HAVING: Create query for Object (group key type may vary)
        QuerySetup setup = setupQueryForObject(bc, ctx.em(), ctx.entityClass());

        // Apply WHERE + GROUP BY setup (returns LocalVar for Gizmo2 scoping)
        LocalVar groupKeyExpr = applyGroupQuerySetup(ctx, setup);

        // Apply HAVING predicate
        Expr havingPredicate = expressionGenerator.generateGroupPredicate(
                bc, ctx.havingExpression(), setup.cb(), setup.root(), groupKeyExpr, ctx.capturedValues());
        applyHavingPredicate(bc, setup.query(), havingPredicate);

        // SELECT groupKey (we'll count results at runtime)
        bc.invokeInterface(CQ_SELECT, setup.query(), groupKeyExpr);

        // Create TypedQuery and get result list
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, ctx.em(), setup.query());
        Expr resultList = bc.invokeInterface(TQ_GET_RESULT_LIST, typedQuery);

        // Return result list size as Long
        Expr size = bc.invokeInterface(LIST_SIZE, resultList);
        Expr sizeLong = bc.invokeVirtual(
                INTEGER_LONG_VALUE,
                bc.invokeStatic(INTEGER_VALUE_OF, size));
        return bc.invokeStatic(LONG_VALUE_OF, sizeLong);
    }

    /** Generates GROUP COUNT without HAVING using COUNT(DISTINCT groupKey). */
    private Expr generateGroupCountWithoutHaving(GroupQueryContext ctx) {
        BlockCreator bc = ctx.bc();

        // Without HAVING: Create query for Long (count result)
        QuerySetup setup = setupQueryForLong(bc, ctx.em(), ctx.entityClass());

        // Apply WHERE and generate group key (no GROUP BY needed for COUNT DISTINCT)
        Expr groupKeyExpr = applyWhereAndGenerateGroupKey(ctx, setup);

        // Simple COUNT(DISTINCT groupKey)
        Expr countExpr = bc.invokeInterface(CB_COUNT_DISTINCT, setup.cb(), groupKeyExpr);
        bc.invokeInterface(CQ_SELECT, setup.query(), countExpr);

        // Create TypedQuery and return getSingleResult()
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, ctx.em(), setup.query());
        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /**
     * Applies HAVING clause predicate to CriteriaQuery.
     */
    private void applyHavingPredicate(BlockCreator bc, Expr query, Expr predicate) {
        if (predicate != null) {
            Expr predicateArray = GizmoHelper.createElementArray(bc, Predicate.class, predicate);
            bc.invokeInterface(CQ_HAVING, query, predicateArray);
        }
    }

    /**
     * Applies ORDER BY clause for GROUP BY queries.
     */
    private void applyGroupOrderBy(
            BlockCreator bc,
            Expr query,
            Expr root,
            Expr groupKeyExpr,
            Expr cb,
            List<?> sortExpressions,
            Expr capturedValues) {

        GizmoHelper.buildOrderByClause(bc, query, cb, sortExpressions,
                sortExpr -> expressionGenerator.generateGroupSortExpression(
                        bc, sortExpr.keyExtractor(), cb, root, groupKeyExpr, capturedValues));
    }

    /** Generates LIST query with WHERE, SELECT, ORDER BY, and pagination. */
    private Expr generateListQueryBody(
            QueryGenContext ctx,
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression) {

        // Combined WHERE + SELECT query
        if (predicateExpression != null && projectionExpression != null) {
            return generateCombinedWhereSelectQuery(ctx, predicateExpression, projectionExpression);
        }

        // Projection query (select().toList())
        if (projectionExpression != null) {
            return generateProjectionQuery(ctx, projectionExpression);
        }

        // Both predicate and no-predicate paths share the same query execution flow
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), ctx.entityClass());

        // Apply WHERE predicate if present (with subquery support)
        if (predicateExpression != null) {
            Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                    ctx.bc(), predicateExpression, setup.cb(), setup.query(), setup.root(), ctx.capturedValues());
            clauseApplier.applyWherePredicate(ctx.bc(), setup.query(), predicate);
        }

        // Execute common list query flow: ORDER BY, DISTINCT, pagination, getResultList()
        return executeListQuery(ctx, setup);
    }

    /** Executes list query: ORDER BY, DISTINCT, pagination, getResultList(). */
    private Expr executeListQuery(QueryGenContext ctx, QuerySetup setup) {
        applyOrderBy(ctx.bc(), setup.query(), setup.root(), setup.cb(),
                ctx.sortExpressions(), ctx.capturedValues(), null);
        clauseApplier.applyDistinct(ctx.bc(), setup.query(), ctx.distinct());
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery",
                ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), setup.query()));
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates COUNT query with subquery support. */
    private Expr generateCountQueryBody(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression expression,
            Expr capturedValues) {

        QuerySetup setup = setupQueryForLong(bc, em, entityClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();
        Expr countExpr = bc.invokeInterface(CB_COUNT, cb, root);
        bc.invokeInterface(CQ_SELECT, query, countExpr);
        Expr predicate = expressionGenerator.generatePredicateWithSubqueries(bc, expression, cb, query, root, capturedValues);
        clauseApplier.applyWherePredicate(bc, query, predicate);
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, em, query);
        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /** Generates aggregation query (MIN, MAX, AVG, SUM) with optional WHERE. */
    private Expr generateAggregationQueryBody(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression predicateExpression,
            LambdaExpression aggregationExpression,
            String aggregationType,
            Expr capturedValues) {

        // Determine result type based on aggregation type
        Class<?> resultType = getAggregationResultType(aggregationType);
        Expr resultClass = Const.of(resultType);

        // Setup query with the aggregation result type
        QuerySetup setup = setupQuery(bc, em, entityClass, resultClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate expression for aggregation mapper (e.g., root.get("salary"))
        Expr mapperExpr = expressionGenerator.generateExpression(
                bc, aggregationExpression, cb, root, capturedValues);

        // Apply aggregation function
        Expr aggExpr = applyAggregationFunction(bc, cb, mapperExpr, aggregationType);

        // SELECT aggregation result
        bc.invokeInterface(CQ_SELECT, query, aggExpr);

        // Apply WHERE predicate if present (with subquery support)
        if (predicateExpression != null) {
            Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                    bc, predicateExpression, cb, query, root, capturedValues);
            clauseApplier.applyWherePredicate(bc, query, predicate);
        }

        // Create and execute query
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, em, query);

        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /** Maps aggregation type to Java result type (AVG->Double, SUM->Long, etc). */
    private Class<?> getAggregationResultType(String aggregationType) {
        return switch (aggregationType) {
            case AGG_TYPE_AVG -> Double.class; // AVG always returns Double
            case AGG_TYPE_SUM_INTEGER -> Long.class; // SUM of integers returns Long
            case AGG_TYPE_SUM_LONG -> Long.class; // SUM of longs returns Long
            case AGG_TYPE_SUM_DOUBLE -> Double.class; // SUM of doubles returns Double
            case AGG_TYPE_MIN, AGG_TYPE_MAX -> Object.class; // MIN/MAX return same type as field (use Object for now)
            default -> throw new IllegalArgumentException(unknownAggregationType(aggregationType));
        };
    }

    /** Generates cb.min(), cb.max(), cb.avg(), or cb.sum() call. */
    private Expr applyAggregationFunction(
            BlockCreator bc,
            Expr cb,
            Expr expression,
            String aggregationType) {

        return switch (aggregationType) {
            case AGG_TYPE_MIN -> bc.invokeInterface(CB_MIN, cb, expression);
            case AGG_TYPE_MAX -> bc.invokeInterface(CB_MAX, cb, expression);
            case AGG_TYPE_AVG -> bc.invokeInterface(CB_AVG, cb, expression);
            case AGG_TYPE_SUM_INTEGER -> bc.invokeInterface(CB_SUM_AS_LONG, cb, expression); // Use sumAsLong for Integer fields
            case AGG_TYPE_SUM_LONG -> bc.invokeInterface(CB_SUM_AS_LONG, cb, expression);
            case AGG_TYPE_SUM_DOUBLE -> bc.invokeInterface(CB_SUM_AS_DOUBLE, cb, expression);
            default -> throw new IllegalArgumentException(unknownAggregationType(aggregationType));
        };
    }

    /** Generates JOIN COUNT query with relationship navigation and bi-entity predicates. */
    private Expr generateJoinCountQueryBody(
            BlockCreator bc,
            Expr em,
            Expr entityClass,
            LambdaExpression joinRelationshipExpression,
            LambdaExpression biEntityPredicateExpression,
            CallSite.JoinType joinType,
            Expr capturedValues) {

        // Setup query for Long (count result)
        QuerySetup setup = setupQueryForLong(bc, em, entityClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Extract relationship field name from join relationship expression
        String relationshipFieldName = joinRelationshipExpression.getFieldNameOrThrow();

        // Create Join by calling root.join(relationshipFieldName, JoinType)
        Expr relationshipName = Const.of(relationshipFieldName);
        Expr jpaJoinType = GizmoHelper.loadJpaJoinType(joinType);
        Expr joinHandle = bc.invokeInterface(FROM_JOIN, root, relationshipName, jpaJoinType);

        // SELECT COUNT(root)
        Expr countExpr = bc.invokeInterface(CB_COUNT, cb, root);
        bc.invokeInterface(CQ_SELECT, query, countExpr);

        // Apply bi-entity predicate if present
        if (biEntityPredicateExpression != null) {
            Expr predicate = expressionGenerator.generateBiEntityPredicateWithSubqueries(
                    bc, biEntityPredicateExpression, cb, query, root, joinHandle, capturedValues);
            clauseApplier.applyWherePredicate(bc, query, predicate);
        }

        // Create TypedQuery
        Expr typedQuery = bc.invokeInterface(EM_CREATE_QUERY, em, query);

        // Return getSingleResult() for count
        return bc.invokeInterface(TQ_GET_SINGLE_RESULT, typedQuery);
    }

    /** Generates simple field projection: select(p -> p.field).toList(). */
    private Expr generateSimpleFieldProjectionQuery(
            QueryGenContext ctx,
            LambdaExpression.FieldAccess fieldAccess) {

        // Load field type class and setup query
        Expr fieldTypeClass = Const.of(fieldAccess.fieldType());
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), fieldTypeClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate root.get("fieldName")
        // Use LocalVar for path since it's used in multiple operations (Gizmo2 requirement)
        Expr fieldName = Const.of(fieldAccess.fieldName());
        LocalVar path = ctx.bc().localVar("path", ctx.bc().invokeInterface(PATH_GET, root, fieldName));

        // query.select(path)
        ctx.bc().invokeInterface(CQ_SELECT, query, path);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), path);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates projection query for field access or expressions. */
    private Expr generateProjectionQuery(
            QueryGenContext ctx,
            LambdaExpression projectionExpression) {

        // Simple field access projection - use type-safe query
        if (projectionExpression instanceof LambdaExpression.FieldAccess fieldAccess) {
            return generateSimpleFieldProjectionQuery(ctx, fieldAccess);
        }

        // Expression projection - use Object query
        QuerySetup setup = setupQueryForObject(ctx.bc(), ctx.em(), ctx.entityClass());
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate the projection expression as JPA Expression
        // Use LocalVar since projectionExpr is used in multiple operations (Gizmo2 requirement)
        LocalVar projectionExpr = ctx.bc().localVar("projectionExpr", expressionGenerator.generateExpressionAsJpaExpression(
                ctx.bc(), projectionExpression, cb, root, ctx.capturedValues()));

        // query.select(projectionExpr)
        ctx.bc().invokeInterface(CQ_SELECT, query, projectionExpr);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), projectionExpr);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Generates combined WHERE + SELECT query. */
    private Expr generateCombinedWhereSelectQuery(
            QueryGenContext ctx,
            LambdaExpression predicateExpression,
            LambdaExpression projectionExpression) {

        // Determine result type based on projection expression
        Expr resultTypeClass;
        if (projectionExpression instanceof LambdaExpression.FieldAccess(_, var fieldType)) {
            // Field access projection - use field type for type safety
            resultTypeClass = Const.of(fieldType);
        } else {
            // Expression projection - use Object.class
            resultTypeClass = Const.of(Object.class);
        }

        // Setup query with the determined result type
        QuerySetup setup = setupQuery(ctx.bc(), ctx.em(), ctx.entityClass(), resultTypeClass);
        Expr cb = setup.cb();
        Expr query = setup.query();
        Expr root = setup.root();

        // Generate WHERE predicate (with subquery support)
        Expr predicate = expressionGenerator.generatePredicateWithSubqueries(
                ctx.bc(), predicateExpression, cb, query, root, ctx.capturedValues());
        clauseApplier.applyWherePredicate(ctx.bc(), query, predicate);

        // Generate SELECT projection expression
        // Use LocalVar since projectionExpr is used in multiple operations (Gizmo2 requirement)
        LocalVar projectionExpr;
        if (projectionExpression instanceof LambdaExpression.FieldAccess(var projFieldName, _)) {
            // Simple field access - root.get("fieldName")
            Expr fieldNameHandle = Const.of(projFieldName);
            projectionExpr = ctx.bc().localVar("projectionExpr", ctx.bc().invokeInterface(PATH_GET, root, fieldNameHandle));
        } else {
            // Expression projection - use expression generator
            projectionExpr = ctx.bc().localVar("projectionExpr", expressionGenerator.generateExpressionAsJpaExpression(
                    ctx.bc(), projectionExpression, cb, root, ctx.capturedValues()));
        }

        // query.select(projectionExpr)
        ctx.bc().invokeInterface(CQ_SELECT, query, projectionExpr);

        // Apply ORDER BY if sorting expressions present
        applyOrderBy(ctx.bc(), query, root, cb, ctx.sortExpressions(), ctx.capturedValues(), projectionExpr);

        // Apply DISTINCT if requested
        clauseApplier.applyDistinct(ctx.bc(), query, ctx.distinct());

        // Create TypedQuery
        // Use LocalVar for values used across multiple operations (Gizmo2 requirement)
        LocalVar typedQuery = ctx.bc().localVar("typedQuery", ctx.bc().invokeInterface(EM_CREATE_QUERY, ctx.em(), query));

        // Apply pagination
        clauseApplier.applyPagination(ctx.bc(), typedQuery, ctx.offset(), ctx.limit());

        // Return getResultList()
        return ctx.bc().invokeInterface(TQ_GET_RESULT_LIST, typedQuery);
    }

    /** Applies ORDER BY, using projectionExpression as fallback for identity sorts. */
    private void applyOrderBy(
            BlockCreator bc,
            Expr query,
            Expr root,
            Expr cb,
            List<?> sortExpressions,
            Expr capturedValues,
            Expr projectionExpression) {

        GizmoHelper.buildOrderByClause(bc, query, cb, sortExpressions, sortExpr -> {
            // Generate JPA Expression for the sort key extractor
            Expr sortKeyExpr = expressionGenerator.generateExpressionAsJpaExpression(
                    bc, sortExpr.keyExtractor(), cb, root, capturedValues);

            // If sort key is null (identity function like s -> s after projection),
            // use the projection expression instead
            if (sortKeyExpr == null && projectionExpression != null) {
                return projectionExpression;
            }
            return sortKeyExpr;
        });
    }
}
