package io.quarkus.qusaq.deployment.criteria;

import io.quarkus.gizmo.ClassCreator;
import io.quarkus.gizmo.ClassOutput;
import io.quarkus.gizmo.MethodCreator;
import io.quarkus.gizmo.ResultHandle;
import io.quarkus.qusaq.deployment.LambdaExpression;
import io.quarkus.qusaq.deployment.analysis.LambdaBytecodeAnalyzer;
import io.quarkus.qusaq.deployment.generation.CriteriaExpressionGenerator;
import org.jboss.logging.Logger;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Handle;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InvokeDynamicInsnNode;
import org.objectweb.asm.tree.MethodNode;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Base class for Criteria query structure verification tests.
 *
 * <p>This test infrastructure verifies that lambda expressions are correctly
 * transformed into JPA Criteria API query structures by:
 * <ol>
 *   <li>Analyzing lambda bytecode to extract AST</li>
 *   <li>Using QusaqProcessor to generate Criteria query building bytecode</li>
 *   <li>Inspecting the generated bytecode to verify correct Criteria API calls</li>
 * </ol>
 *
 * <p><strong>No Database or Execution Required</strong>: These tests verify
 * the bytecode generation logic without executing queries or requiring a database.
 *
 * <p><strong>Testing Approach</strong>:
 * <pre>
 * Lambda Expression (p -> p.age > 30)
 *     ↓ (bytecode analysis)
 * Lambda AST (BinaryOp[GT, FieldAccess[age], Constant[30]])
 *     ↓ (Criteria generation)
 * Generated Bytecode
 *     ↓ (bytecode inspection)
 * Verify: greaterThan method invocation found
 * Verify: "age" constant found (for root.get("age"))
 * Verify: 30 constant found
 * </pre>
 */
public abstract class CriteriaQueryTestBase {

    private static final Logger log = Logger.getLogger(CriteriaQueryTestBase.class);

    private static final String SOURCES_CLASS_NAME = "io.quarkus.qusaq.deployment.testutil.LambdaTestSources";
    private static ClassNode sourcesClassNode;

    /**
     * Analyzes a lambda method from LambdaTestSources and returns its AST.
     */
    protected LambdaExpression analyzeLambda(String methodName) {
        try {
            if (sourcesClassNode == null) {
                sourcesClassNode = loadSourcesClass();
            }

            MethodNode sourceMethod = findMethod(sourcesClassNode, methodName);
            InvokeDynamicInsnNode invokeDynamic = findInvokeDynamic(sourceMethod);
            Handle lambdaHandle = extractLambdaHandle(invokeDynamic);

            // Get the class bytecode for the analyzer
            String classFile = SOURCES_CLASS_NAME.replace('.', '/') + ".class";
            byte[] classBytes;
            try (InputStream is = getClass().getClassLoader().getResourceAsStream(classFile)) {
                if (is == null) {
                    throw new RuntimeException("Cannot find test sources class: " + classFile);
                }
                classBytes = is.readAllBytes();
            }

            // Use the LambdaBytecodeAnalyzer directly
            LambdaBytecodeAnalyzer analyzer = new LambdaBytecodeAnalyzer();
            return analyzer.analyze(classBytes, lambdaHandle.getName(), lambdaHandle.getDesc());
        } catch (Exception e) {
            throw new RuntimeException("Failed to analyze lambda: " + methodName, e);
        }
    }

    /**
     * Generates Criteria query building bytecode for the given lambda expression.
     */
    protected CriteriaQueryStructure generateCriteriaQuery(LambdaExpression expression) {
        return generateCriteriaQuery(expression, "TestEntity");
    }

    /**
     * Generates Criteria query building bytecode and inspects it for verification.
     */
    protected CriteriaQueryStructure generateCriteriaQuery(LambdaExpression expression, String entityName) {
        CriteriaQueryStructure structure = new CriteriaQueryStructure(entityName);

        try {
            // Generate a unique class name
            String className = "io.quarkus.qusaq.test.TestQueryExecutor_" + System.nanoTime();

            // Capture generated bytecode
            Map<String, byte[]> classData = new HashMap<>();
            ClassOutput classOutput = classData::put;

            // Generate the bytecode
            try (ClassCreator classCreator = ClassCreator.builder()
                    .classOutput(classOutput)
                    .className(className)
                    .build()) {

                // Create a method that builds the Criteria query
                try (MethodCreator method = classCreator.getMethodCreator(
                        "buildPredicate",
                        jakarta.persistence.criteria.Predicate.class,
                        jakarta.persistence.criteria.CriteriaBuilder.class,
                        jakarta.persistence.criteria.Root.class,
                        Object[].class)) {

                    ResultHandle cb = method.getMethodParam(0);
                    ResultHandle root = method.getMethodParam(1);
                    ResultHandle capturedValues = method.getMethodParam(2);

                    // Generate the predicate building code using CriteriaExpressionGenerator directly
                    CriteriaExpressionGenerator generator = new CriteriaExpressionGenerator();
                    ResultHandle predicate = generator.generatePredicate(method, expression, cb, root, capturedValues);

                    structure.setPredicateGenerated(predicate != null);
                    method.returnValue(predicate);
                }
            }

            // Get the generated bytecode
            String classFileName = className.replace('.', '/');
            byte[] bytecode = classData.get(classFileName);

            if (bytecode != null) {
                // Inspect the bytecode
                BytecodeInspector inspector = new BytecodeInspector(bytecode);
                structure.setInspector(inspector);
                structure.setGenerationSuccessful(true);
            } else {
                structure.setGenerationSuccessful(false);
                structure.setErrorMessage("No bytecode generated");
            }

        } catch (Exception e) {
            log.errorf(e, "Failed to generate Criteria query for expression: %s", expression);
            structure.setGenerationSuccessful(false);
            structure.setErrorMessage(e.getMessage());
        }

        return structure;
    }

    /**
     * Verifies that Criteria query generation succeeds.
     */
    protected void assertCriteriaGenerationSucceeds(LambdaExpression expression) {
        CriteriaQueryStructure structure = generateCriteriaQuery(expression);
        assertThat(structure.isGenerationSuccessful())
                .as("Criteria query generation should succeed for: " + expression)
                .isTrue();
        assertThat(structure.isPredicateGenerated())
                .as("Predicate should be generated for: " + expression)
                .isTrue();
    }

    /**
     * Full test pattern: analyze lambda + verify Criteria generation succeeds.
     */
    protected void testCriteriaGeneration(String lambdaMethodName) {
        LambdaExpression expr = analyzeLambda(lambdaMethodName);
        assertCriteriaGenerationSucceeds(expr);
    }

    // ==================== ASSERTION HELPERS ====================

    /**
     * Asserts that a specific Criteria API method was called.
     */
    protected void assertCriteriaMethodCalled(CriteriaQueryStructure structure, String methodName) {
        boolean called = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isMethod(methodName));
        assertThat(called)
                .as("Method " + methodName + " should have been called")
                .isTrue();
    }

    /**
     * Asserts that a specific method was called a certain number of times.
     */
    protected void assertCriteriaMethodCallCount(CriteriaQueryStructure structure, String methodName, int expectedCount) {
        long count = structure.getInvocations().stream()
                .filter(inv -> inv.isMethod(methodName))
                .count();
        assertThat(count)
                .as("Method " + methodName + " call count")
                .isEqualTo(expectedCount);
    }

    /**
     * Asserts that a field name appears as a constant (for root.get("fieldName")).
     */
    protected void assertFieldAccessed(CriteriaQueryStructure structure, String fieldName) {
        boolean accessed = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isConstant(fieldName));
        assertThat(accessed)
                .as("Field '" + fieldName + "' should appear as a constant (for root.get)")
                .isTrue();
    }

    /**
     * Asserts that a constant value was used.
     */
    protected void assertConstantUsed(CriteriaQueryStructure structure, Object constantValue) {
        boolean found = structure.getInvocations().stream()
                .anyMatch(inv -> inv.isConstant(constantValue));
        assertThat(found)
                .as("Constant value '" + constantValue + "' should have been used")
                .isTrue();
    }

    /**
     * Asserts that specific Criteria API methods were called.
     */
    protected void assertCriteriaStructure(CriteriaQueryStructure structure, String... expectedMethods) {
        for (String expectedMethod : expectedMethods) {
            assertCriteriaMethodCalled(structure, expectedMethod);
        }
    }

    // Helper methods for loading lambda sources

    private ClassNode loadSourcesClass() throws Exception {
        String classFile = SOURCES_CLASS_NAME.replace('.', '/') + ".class";
        try (InputStream is = getClass().getClassLoader().getResourceAsStream(classFile)) {
            if (is == null) {
                throw new RuntimeException("Cannot find test sources class: " + classFile);
            }
            ClassReader reader = new ClassReader(is);
            ClassNode classNode = new ClassNode();
            reader.accept(classNode, 0);
            return classNode;
        }
    }

    private MethodNode findMethod(ClassNode classNode, String methodName) {
        return classNode.methods.stream()
                .filter(m -> m.name.equals(methodName))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("Method not found: " + methodName));
    }

    private InvokeDynamicInsnNode findInvokeDynamic(MethodNode method) {
        for (var insn : method.instructions) {
            if (insn instanceof InvokeDynamicInsnNode) {
                return (InvokeDynamicInsnNode) insn;
            }
        }
        throw new RuntimeException("No invokedynamic in " + method.name);
    }

    private Handle extractLambdaHandle(InvokeDynamicInsnNode invokeDynamic) {
        if (invokeDynamic.bsmArgs == null || invokeDynamic.bsmArgs.length < 2) {
            throw new RuntimeException("Invalid invokedynamic args");
        }
        return (Handle) invokeDynamic.bsmArgs[1];
    }

    /**
     * Represents the structure of a generated Criteria query for verification.
     */
    protected static class CriteriaQueryStructure {
        private final String entityName;
        private BytecodeInspector inspector;
        private boolean generationSuccessful;
        private boolean predicateGenerated;
        private String errorMessage;

        public CriteriaQueryStructure(String entityName) {
            this.entityName = entityName;
        }

        public String getEntityName() {
            return entityName;
        }

        public void setInspector(BytecodeInspector inspector) {
            this.inspector = inspector;
        }

        public boolean isGenerationSuccessful() {
            return generationSuccessful;
        }

        public void setGenerationSuccessful(boolean successful) {
            this.generationSuccessful = successful;
        }

        public boolean isPredicateGenerated() {
            return predicateGenerated;
        }

        public void setPredicateGenerated(boolean generated) {
            this.predicateGenerated = generated;
        }

        public String getErrorMessage() {
            return errorMessage;
        }

        public void setErrorMessage(String message) {
            this.errorMessage = message;
        }

        /**
         * Gets all method invocations found in the generated bytecode.
         */
        public List<BytecodeInspector.MethodInvocation> getInvocations() {
            return inspector != null ? inspector.getInvocations() : List.of();
        }

        @Override
        public String toString() {
            return "CriteriaQueryStructure{" +
                   "entityName='" + entityName + '\'' +
                   ", generationSuccessful=" + generationSuccessful +
                   ", predicateGenerated=" + predicateGenerated +
                   ", invocations=" + (inspector != null ? inspector.getInvocations().size() : 0) +
                   ", errorMessage='" + errorMessage + '\'' +
                   '}';
        }
    }
}
