package io.quarkiverse.qubit.deployment.jfr;

import jdk.jfr.Category;
import jdk.jfr.Description;
import jdk.jfr.Event;
import jdk.jfr.Label;
import jdk.jfr.Name;
import jdk.jfr.StackTrace;

/**
 * JFR event for code generation of query executors.
 * <p>
 * Records timing for generating individual executor classes with Gizmo.
 */
@Name("io.quarkiverse.qubit.CodeGen")
@Label("Qubit Code Generation")
@Category({"Qubit", "CodeGen"})
@Description("Query executor code generation timing")
@StackTrace(false)
public class QubitCodeGenEvent extends Event {

    @Label("Lambda Hash")
    @Description("Hash identifier for the generated executor")
    public String lambdaHash;

    @Label("Query Type")
    @Description("Type of query being generated")
    public String queryType;

    @Label("Generated Class")
    @Description("Fully qualified name of generated class")
    public String generatedClass;

    @Label("Bytecode Size")
    @Description("Size of generated bytecode in bytes")
    public int bytecodeSize;

    @Label("Captured Vars")
    @Description("Number of captured variables")
    public int capturedVarCount;

    /**
     * Creates and starts a code generation event.
     */
    public static QubitCodeGenEvent start(String lambdaHash, String queryType) {
        QubitCodeGenEvent event = new QubitCodeGenEvent();
        event.lambdaHash = lambdaHash != null && lambdaHash.length() > 8
                ? lambdaHash.substring(0, 8) : lambdaHash;
        event.queryType = queryType;
        event.begin();
        return event;
    }

    /**
     * Completes the code generation event and commits it.
     */
    public void complete(String generatedClass, int bytecodeSize, int capturedVarCount) {
        this.generatedClass = generatedClass;
        this.bytecodeSize = bytecodeSize;
        this.capturedVarCount = capturedVarCount;
        this.end();
        this.commit();
    }
}
