package io.quarkiverse.qubit.deployment.common;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link EntityClassInfo} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractEntityClassInfoAssert<S extends AbstractEntityClassInfoAssert<S, A>, A extends EntityClassInfo>
        extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractEntityClassInfoAssert}</code> to make assertions on actual EntityClassInfo.
     *
     * @param actual the EntityClassInfo we want to make assertions on.
     */
    protected AbstractEntityClassInfoAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual EntityClassInfo's effectiveClassName is equal to the given one.
     *
     * @param effectiveClassName the given effectiveClassName to compare the actual EntityClassInfo's effectiveClassName to.
     * @return this assertion object.
     * @throws AssertionError - if the actual EntityClassInfo's effectiveClassName is not equal to the given one.
     */
    public S hasEffectiveClassName(String effectiveClassName) {
        // check that actual EntityClassInfo we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting effectiveClassName of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        String actualEffectiveClassName = actual.getEffectiveClassName();
        if (!Objects.areEqual(actualEffectiveClassName, effectiveClassName)) {
            failWithMessage(assertjErrorMessage, actual, effectiveClassName, actualEffectiveClassName);
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual EntityClassInfo is placeholder.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual EntityClassInfo is not placeholder.
     */
    public S isPlaceholder() {
        // check that actual EntityClassInfo we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is true
        if (!actual.isPlaceholder()) {
            failWithMessage("\nExpecting that actual EntityClassInfo is placeholder but is not.");
        }

        // return the current assertion for method chaining
        return myself;
    }

    /**
     * Verifies that the actual EntityClassInfo is not placeholder.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual EntityClassInfo is placeholder.
     */
    public S isNotPlaceholder() {
        // check that actual EntityClassInfo we want to make assertions on is not null.
        isNotNull();

        // check that property call/field access is false
        if (actual.isPlaceholder()) {
            failWithMessage("\nExpecting that actual EntityClassInfo is not placeholder but is.");
        }

        // return the current assertion for method chaining
        return myself;
    }

}
