package io.quarkiverse.qubit.deployment.common;

/**
 * {@link EntityClassInfo} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractEntityClassInfoAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class EntityClassInfoAssert extends AbstractEntityClassInfoAssert<EntityClassInfoAssert, EntityClassInfo> {

    /**
     * Creates a new <code>{@link EntityClassInfoAssert}</code> to make assertions on actual EntityClassInfo.
     *
     * @param actual the EntityClassInfo we want to make assertions on.
     */
    public EntityClassInfoAssert(EntityClassInfo actual) {
        super(actual, EntityClassInfoAssert.class);
    }

    /**
     * An entry point for EntityClassInfoAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myEntityClassInfo)</code> and get specific assertion with
     * code completion.
     *
     * @param actual the EntityClassInfo we want to make assertions on.
     * @return a new <code>{@link EntityClassInfoAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static EntityClassInfoAssert assertThat(EntityClassInfo actual) {
        return new EntityClassInfoAssert(actual);
    }
}
