quarkus.datasource.db-kind=${db.kind:h2}
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=docker.io/library/postgres:17
quarkus.datasource.devservices.command=-c shared_preload_libraries=pg_stat_statements
quarkus.datasource.devservices.init-script-path=init-pg-stat-statements.sql
%h2.quarkus.datasource.devservices.enabled=false
%h2.quarkus.datasource.jdbc.url=jdbc:h2:mem:benchmark;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.log.level=WARN
